TencentBlueKing/blueking-paas

apiserver/paasng/paasng/pluginscenter/configuration.py, apiserver/paasng/paasng/pluginscenter/constants.py, apiserver/paasng/paasng/pluginscenter/exceptions.py, apiserver/paasng/paasng/pluginscenter/handlers.py, apiserver/paasng/paasng/pluginscenter/models/instances.py, apiserver/paasng/paasng/pluginscenter/releases/executor.py, apiserver/paasng/paasng/pluginscenter/releases/stages.py, apiserver/paasng/paasng/pluginscenter/shim.py, apiserver/paasng/paasng/pluginscenter/sourcectl/tencent.py, apiserver/paasng/paasng/pluginscenter/thirdparty/deploy.py, apiserver/paasng/paasng/pluginscenter/urls.py, apiserver/paasng/paasng/pluginscenter/views.py, apiserver/paasng/tests/pluginscenter/conftest.py, apiserver/paasng/tests/pluginscenter/release/test_executor.py, apiserver/paasng/tests/pluginscenter/release/test_steps.py
- feature: 「插件开发者中心」支持重试失败的发布版本、失败的发布步骤、回退到上一步
- refactor: 重构插件开发者中心的发布步骤逻辑(重构抽象);
=> feature: 「插件开发者中心」支持重试失败的发布版本、失败的发布步骤、回退到上一步。

webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/custom-domain.vue, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue, webfe/package_vue/src/views/dev-center/create-app/success-git.scss, webfe/package_vue/src/views/dev-center/create-app/success-git.vue
fix: 独立域名提示信息优化。进程管理名过长时样式乱了。开发者中心：创建插件成功后提示信息修改
=> fix: 独立域名提示信息优化。进程管理名过长时样式乱了。开发者中心：创建插件成功后提示信息修改

workloads/paas_wl/paas_wl/cnative/specs/events.py, workloads/paas_wl/paas_wl/cnative/specs/serializers.py, workloads/paas_wl/paas_wl/cnative/specs/views_enduser.py, workloads/paas_wl/paas_wl/resources/base/kres.py
=> feature: 云原生应用查询部署状态时返回实时的 k8s 事件列表

apiserver/paasng/paasng/engine/deploy/infras.py, apiserver/paasng/paasng/engine/signals.py, apiserver/paasng/paasng/publish/entrance/exposer.py, apiserver/paasng/tests/publish/test_entrance.py
- Add cache on get_live_addresses to improve performance
=> Add cache on get_live_addresses to improve performance

apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/configuration/templates.html, workloads/paas_wl/paas_wl/networking/ingress/domains/independent.py, workloads/paas_wl/paas_wl/networking/ingress/domains/manager.py, workloads/paas_wl/paas_wl/resources/base/controllers.py, workloads/paas_wl/tests/resources/base/test_kres.py
Fix:
- duplicated vue method
- failing unit-test in Kind cluster because the behaviour of default scheduler 
- unable to add custom domains
=> Fix add custom domains

apiserver/paasng/paasng/publish/entrance/exposer.py
Disable cache for `list_custom_addresses` function to avoid data inconsistency
=> Disable cache for `list_custom_addresses` function

workloads/paas_wl/paas_wl/resources/base/controllers.py, workloads/paas_wl/tests/resources/base/test_controllers.py
=> bugfix: 修复挂载 sidecar 的 Pod 不会被清理

apiserver/paasng/assets/javascripts/api/index.js, webfe/package_vue/src/api/index.js, webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/router/index.js, webfe/package_vue/src/views/plugin-center/create-plugin/index.vue, webfe/package_vue/src/views/plugin-center/index.vue, webfe/package_vue/src/views/plugin-center/plugin/base-config/base-info.vue, webfe/package_vue/src/views/plugin-center/plugin/version-manager/release-stages/market.vue
- 插件列表添加创建时间项
- 完善市场信息默认取创建人为应用联系人，详情描述去掉必填
=> fix: 插件列表添加创建时间，完善市场信息默认取创建人为应用联系人

webfe/package_vue/src/views/plugin-center/index.vue, webfe/package_vue/src/views/plugin-center/plugin/base-config/market-info-edit.vue, webfe/package_vue/src/views/plugin-center/plugin/log/access-log.vue, webfe/package_vue/src/views/plugin-center/plugin/log/custom-log.vue, webfe/package_vue/src/views/plugin-center/plugin/version-manager/release-stages/market.vue
- 插件列表：去掉 状态 列
- 插件列表：英文时小屏操作展示不全
- 应用分类：tooltips 需要按设计规范添加样式
- 日志时间显示问题
=> fix: 插件列表：去除状态列、英文时小屏操作显示不全；应用分类tooltips规范；日志显示时间问题修复

webfe/package_vue/src/views/dev-center/app/engine/log/access-log.vue
=> fix: 访问日志查询筛选功能的高度太低

apiserver/paasng/paasng/engine/controller/client.py, apiserver/paasng/paasng/engine/deploy/async_comps.py, apiserver/paasng/paasng/engine/deploy/engine_svc.py, apiserver/paasng/paasng/engine/deploy/preparations.py, apiserver/paasng/paasng/engine/deploy/release.py, apiserver/paasng/paasng/engine/models/base.py, apiserver/paasng/paasng/engine/models/deployment.py, apiserver/paasng/paasng/engine/monitoring.py, apiserver/paasng/paasng/engine/views.py, apiserver/paasng/paasng/settings/workloads.py, apiserver/paasng/tests/engine/test_monitoring.py, apiserver/paasng/tests/utils/mocks/engine.py, workloads/paas_wl/paas_wl/platform/applications/models/app.py, workloads/paas_wl/paas_wl/platform/applications/models/config.py, workloads/paas_wl/paas_wl/platform/applications/struct_models.py, workloads/paas_wl/paas_wl/platform/external/client.py, workloads/paas_wl/paas_wl/platform/external/local.py, workloads/paas_wl/paas_wl/platform/misc/probe.py, workloads/paas_wl/paas_wl/release_controller/process/callbacks.py, workloads/paas_wl/paas_wl/utils/redisdb.py
Related APIs:
- Create new buildprocess object
=> Move build/deploy related API from workloads service to module

apiserver/paasng/paasng/engine/deploy/engine_svc.py, apiserver/paasng/paasng/engine/management/commands/inject_engineapp_metadata.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/tests/engine/test_engine_svc.py, apiserver/paasng/tests/paas_wl/conftest.py, apiserver/paasng/tests/paas_wl/networking/test_api.py, apiserver/paasng/tests/paas_wl/platform/test_api.py, apiserver/paasng/tests/utils/helpers.py, workloads/paas_wl/paas_wl/networking/api.py, workloads/paas_wl/paas_wl/platform/api.py
Refactor metadata related functions and fix some unit tests.
=> Refactor metadata related functions and fix some unit tests.

apiserver/paasng/paasng/engine/deploy/engine_svc.py, apiserver/paasng/tests/conftest.py, apiserver/paasng/tests/engine/test_engine_svc.py, apiserver/paasng/tests/engine/test_infras.py, apiserver/paasng/tests/engine/test_preparations.py, apiserver/paasng/tests/paas_wl/conftest.py, apiserver/paasng/tests/paas_wl/platform/test_api.py, workloads/paas_wl/paas_wl/platform/api.py
Fix most of the tests under "engine" directory
=> Fix most of the tests under "engine" directory

apiserver/paasng/paasng/engine/controller/client.py, apiserver/paasng/paasng/engine/models/base.py, apiserver/paasng/paasng/engine/models/deployment.py, apiserver/paasng/paasng/engine/models/managers.py, apiserver/paasng/paasng/engine/views.py, apiserver/paasng/paasng/platform/applications/models.py, apiserver/paasng/tests/engine/models/test_deployment.py, apiserver/paasng/tests/paas_wl/platform/test_api.py, apiserver/paasng/tests/paas_wl/release_controller/test_api.py, apiserver/paasng/tests/utils/mocks/engine.py, workloads/paas_wl/paas_wl/platform/api.py, workloads/paas_wl/paas_wl/release_controller/api.py, workloads/paas_wl/paas_wl/release_controller/builder/exceptions.py, workloads/paas_wl/paas_wl/resources/actions/delete.py
Migrate "app__delete" and 3 other API calls into local procedure call
=> Migrate "app__delete" and 3 other API calls into local procedure call

apiserver/paasng/tests/paas_wl/conftest.py, apiserver/paasng/tests/paas_wl/release_controller/builder/__init__.py, apiserver/paasng/tests/paas_wl/release_controller/builder/test_executor.py, apiserver/paasng/tests/paas_wl/release_controller/builder/test_infras.py, apiserver/paasng/tests/paas_wl/release_controller/builder/test_procedures.py, apiserver/paasng/tests/paas_wl/release_controller/process/conftest.py, apiserver/paasng/tests/paas_wl/release_controller/process/test_utils.py, apiserver/paasng/tests/paas_wl/release_controller/test_builder.py, apiserver/paasng/tests/paas_wl/release_controller/test_models.py, apiserver/paasng/tests/paas_wl/utils/build.py, apiserver/paasng/tests/paas_wl/utils/wl_app.py
Migrate paas_wl.tests.release_controller
=> Migrate paas_wl.tests.release_controller

apiserver/paasng/paasng/__init__.py, apiserver/paasng/tests/paas_wl/test_utils/test_basic.py, apiserver/paasng/tests/paas_wl/test_utils/test_main.py
Migrate paas_wl.tests.test_utils
=> Migrate paas_wl.tests.test_utils

apiserver/paasng/paas_wl/cnative/specs/views_enduser.py
=> Enhance: when deploy cnative app, validate first, get image credentials later

apiserver/paasng/paasng/engine/deploy/engine_svc.py
Fix: when no images are bound to the app, use default value
=> Fix: when no images are bound to the app, use default value

webfe/package_vue/src/views/dev-center/app/summary/default-overview.vue, webfe/package_vue/src/views/index.vue
=> fix: 非引擎应用跳转概览页

webfe/package_vue/src/components/app-quick-nav.vue
=> fix: 请求 app环境link 优化

webfe/package_vue/src/components/paas-app-nav.vue, webfe/package_vue/src/components/paas-cloud-app-nav.vue, webfe/package_vue/src/views/dev-center/app/basic-config/module-manage.vue
itsm模块管理切换云原生应用 message 报错处理, 从定向到概览页
=> fix: 切换云原生应用 message 报错处理, 从定向到概览页

apiserver/paasng/paasng/engine/workflow/flow.py
=> feat: return the content of ProvisionInstanceError to the frontend

apiserver/paasng/paas_wl/resources/actions/archive.py, apiserver/paasng/paas_wl/workloads/processes/models.py, apiserver/paasng/paasng/engine/deploy/release.py, apiserver/paasng/paasng/engine/models/processes.py, apiserver/paasng/paasng/extensions/declarative/deployment/controller.py, apiserver/paasng/paasng/plat_admin/admin42/views/services.py, apiserver/paasng/paasng/platform/log/views.py, apiserver/paasng/tests/paas_wl/networking/ingress/managers/test_misc.py, apiserver/paasng/tests/paas_wl/workloads/processes/test_models.py
bugfix: 
- 修复应用修改 procfile 但发布失败后, 会导致应用无法下架的问题
- 不允许 Admin42 删除迁移应用增强服务实例(会导致无法重新分配增强服务)
=> bugfix: 修复应用修改 procfile 但发布失败后, 会导致应用无法下架的问题

apiserver/paasng/paasng/settings/__init__.py, apiserver/paasng/paasng/utils/logging.py, apiserver/paasng/tests/conftest.py, apiserver/paasng/tests/platform/mgrlegacy/conftest.py, apiserver/paasng/tests/utils/helpers.py
- Remove legacy app data after each test
- Supress trivial log messages from bkpaas_auth.core
=> Remove legacy app data after each test; Supress trivial log messages from bkpaas_auth.core

apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/client.py
=> refactor: use http schema to access import_config api

apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/high_cpu_usage.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/high_mem_usage.yaml.j2
=> chore: update pod to pod_name in alert rules

webfe/package_vue/src/views/dev-center/create-app/default.scss, webfe/package_vue/src/views/dev-center/create-app/default.vue
=> fix：创建应用页面提单修复

webfe/package_vue/src/components/app-quick-nav.vue
=> fix: 路由切换无需清空快捷访问，切换应用时进行更新

apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/high_cpu_usage.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/high_mem_usage.yaml.j2
=> chore: rename alert rule label BKPAAS to BKAPP

webfe/package_vue/src/assets/css/patch.scss, webfe/package_vue/src/components/ui/git-extend.vue, webfe/package_vue/src/directives/en-class.js, webfe/package_vue/src/views/dev-center/app/basic-config/module-manage.vue, webfe/package_vue/src/views/dev-center/app/create-module/index.scss, webfe/package_vue/src/views/dev-center/app/create-module/index.vue, webfe/package_vue/src/views/dev-center/create-app/common.scss, webfe/package_vue/src/views/dev-center/create-app/default.scss, webfe/package_vue/src/views/dev-center/create-app/default.vue
- 创建应用，新增模块表单高度对齐，以及尺寸调整
- 英文下label尺寸调整
=> 创建应用，新增模块表单高度对齐，以及尺寸调整，英文下label尺寸调整

webfe/package_vue/src/views/dev-center/app/summary/default-overview.vue
=> fix: 概览告警记录字段控制不请求对应接口

webfe/package_vue/src/components/paas-app-nav.vue, webfe/package_vue/src/components/paas-cloud-app-nav.vue
=> fix: 云原生应用部署状态切换到itsm 无权限弹窗问题修复

apiserver/paasng/paasng/engine/streaming/views.py, apiserver/paasng/paasng/extensions/bk_plugins/pluginscenter_views.py
=> fix: close connection for subscriber actively

apiserver/paasng/paas_wl/networking/ingress/certs/utils.py, apiserver/paasng/paas_wl/networking/ingress/management/commands/refresh_cert.py, apiserver/paasng/paas_wl/networking/ingress/management/commands/shared_cert_tool.py, apiserver/paasng/paas_wl/networking/ingress/models.py, apiserver/paasng/tests/paas_wl/networking/ingress/test_models.py
- Enhance refresh_cert command to support "full-scan" flag which update the uninitialized domains
=> Enhance refresh_cert command to support "full-scan" flag which update the uninitialized domains

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/render-list.vue
=> fix: 云api筛选分页bug修复

webfe/package_vue/src/views/dev-center/app/engine/log/standart-log.vue
=> fix: 日志进程名展示问题修复

apiserver/paasng/paas_wl/platform/applications/models/config.py, apiserver/paasng/paas_wl/workloads/images/entities.py, apiserver/paasng/paas_wl/workloads/processes/models.py, apiserver/paasng/paasng/engine/configurations/building.py, apiserver/paasng/paasng/engine/configurations/image.py, apiserver/paasng/paasng/engine/deploy/bg_build/utils.py, apiserver/paasng/paasng/engine/deploy/building.py, apiserver/paasng/paasng/platform/modules/helpers.py, apiserver/paasng/paasng/settings/__init__.py, apiserver/paasng/paasng/utils/i18n/migrate.py, apiserver/paasng/tests/paas_wl/resources/base/test_controllers.py, apiserver/paasng/tests/paas_wl/resources/base/test_credentials.py
feature: 支持 CloudNative Buildpacks 运行时 
- cnb runtime 添加额外的环境变量
- 添加了镜像仓库和镜像凭证相关的配置项
- 修改了进程启动命令的配置
=> feature: 支持 CloudNative Buildpacks 运行时

webfe/package_vue/src/components/app-quick-nav.vue
fix: search dialog z-index bug
=> fix: search dialog z-index bug

webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/views/dev-center/app/engine/app-status/comps/process-operation.vue, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue
=> fix: eslint格式化bug修复

webfe/package_vue/package.json, webfe/package_vue/src/views/dev-center/app/summary/default-overview.vue, webfe/package_vue/src/views/dev-center/app/summary/index.vue
=> Wmh bug dev

apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/high_cpu_usage.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/high_mem_usage.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/oom_killed.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/pod_restart.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/constants.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/metric_label.py, apiserver/paasng/paasng/monitoring/monitor/exceptions.py, apiserver/paasng/paasng/monitoring/monitor/management/commands/init_alert_rules.py, apiserver/paasng/paasng/monitoring/monitor/views.py, apiserver/paasng/tests/monitoring/alert_rules/conftest.py, apiserver/paasng/tests/monitoring/alert_rules/test_api.py, apiserver/paasng/tests/monitoring/alert_rules/test_manager.py, apiserver/paasng/tests/monitoring/test_metric_label.py
app的监控指标中增加bcs_cluster_id label
=> refactor: add bcs_cluster_id in metric labels

webfe/package_vue/src/assets/css/components/patch.scss, webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/views/dev-center/app/basic-config/access-portal/index.vue, webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/app-perm.vue, webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/apply-record.vue, webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/index.vue, webfe/package_vue/src/views/dev-center/app/engine/app-status/comps/process-operation.vue, webfe/package_vue/src/views/dev-center/monitor/index.vue
=> fix: 升级样式问题间距修复

webfe/package_vue/src/components/authentication-info.vue
=> fix: 应用切换秘钥重新获取

webfe/package_vue/src/components/authentication-info.vue, webfe/package_vue/src/views/dev-center/app/basic-config/info.vue, webfe/package_vue/src/views/dev-center/create-app/default.vue
=> fix: 基本信息-获取验证码切换优化，验证码icon对齐

webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue
=> fix: 调整进程列表最低高度

apiserver/paasng/paasng/plat_admin/admin42/views/applications.py, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue
feat: adjust according to design
=> feat: adjust according to design

apiserver/paasng/paasng/plat_admin/admin42/views/applications.py, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue
=> feat: 调整扩缩容功能

apiserver/paasng/paasng/dev_resources/servicehub/services.py, apiserver/paasng/paasng/plat_admin/system/serializers.py, apiserver/paasng/paasng/plat_admin/system/views.py, apiserver/paasng/tests/dev_resources/servicehub/test_services.py, apiserver/paasng/tests/plat_admin/test_system.py
SysAddonsAPIViewSet 增加静默启用(绑定)增强服务的逻辑
=> refactor: add silent binding add-on service logic in SysAddonsAPIViewSet

apiserver/paasng/paasng/plat_admin/system/views.py
=> fix: 204 with data is wrong

apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/high_rabbitmq_queue_messages.yaml.j2
=> refactor: update high rabbitmq queue messages alert rule

operator/pkg/controllers/reconcilers/addons.go, operator/pkg/controllers/reconcilers/addons_test.go
=> fix: end reconcile explicitly when addon provision failed

apiserver/paasng/conf.yaml.tpl, apiserver/paasng/paasng/engine/utils/source.py, apiserver/paasng/paasng/settings/__init__.py, operator/api/v1alpha1/projectconfig_types.go, operator/api/v1alpha2/bkapp_webhook.go, operator/api/v1alpha2/bkapp_webhook_test.go, operator/config/crd/bases/paas.bk.tencent.com_projectconfigs.yaml, operator/pkg/config/config.go
=> feat: add MAX_PROCESSES_PER_MODULE when parse module process

webfe/package_vue/src/components/paas-header.vue
=> feat: 持续化接口成功刷新页面

bkpaas-cli/Readme.md
- Tiny update readme of bkpaas-cli
=> Tiny update readme of bkpaas-cli

webfe/package_vue/src/App.vue, webfe/package_vue/src/assets/css/mixins/ellipsis.scss, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-hook.vue, webfe/package_vue/src/views/dev-center/app/engine/log/access-log.vue, webfe/package_vue/src/views/dev-center/app/engine/log/custom-log.vue, webfe/package_vue/src/views/dev-center/app/engine/log/standart-log.vue, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue, webfe/package_vue/src/views/dev-center/create-app/success-git.vue, webfe/package_vue/src/views/dev-center/create-app/success-simple.vue, webfe/package_vue/src/views/dev-center/create-app/success-smart.vue, webfe/package_vue/src/views/dev-center/create-app/success.vue, webfe/package_vue/src/views/plugin-center/plugin/base-config/base-info.vue, webfe/package_vue/src/views/plugin-center/plugin/log/access-log.vue, webfe/package_vue/src/views/plugin-center/plugin/log/custom-log.vue, webfe/package_vue/src/views/plugin-center/plugin/log/standart-log.vue
- 进程管理样式bug，对应样式优化
- 云原生创建应用loading效果，体验问题修复
=> Fix bug dev

apiserver/paasng/paasng/accounts/management/commands/create_authed_app_user.py, apiserver/paasng/paasng/accounts/middlewares.py, apiserver/paasng/paasng/accounts/utils.py, apiserver/paasng/paasng/extensions/bk_plugins/views.py, apiserver/paasng/paasng/plat_admin/system/views.py, apiserver/paasng/tests/accounts/test_middlewares.py
- Force the system api to authenticated by authed app, include: SysUniApplicationViewSet, SysBkPluginsViewset, SysBkPluginsBatchViewset
=> Force some system APIs to be able to authenticate by authed app

apiserver/paasng/support-files/apigw/definition.yaml, apiserver/paasng/support-files/apigw/resources.yaml
=> chore: add retrieve_addon_specs api in apigw resources

webfe/package_vue/src/views/dev-center/app/basic-config/info.vue
=> style: 删除应用按钮间距

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/index.vue
=> feat: 应用编排标题样式修改

webfe/package_vue/src/language/lang/en.js
=> fix: 生产环境翻译修复

webfe/package_vue/src/views/dev-center/create-app/default.vue
=> fix: 创建应用->普通应用才能展示蓝鲸插件选项

webfe/package_vue/src/views/dev-center/app/engine/app-status/comps/process-event.vue
=> fix: 修复云原生应用事件表格宽度问题

webfe/package_vue/src/views/dev-center/create-app/default.vue
=> fix: 创建应用，蓝鲸插件tab切换bug修复

apiserver/paasng/paasng/monitoring/monitor/alert_rules/handlers.py
=> refactor: not use monitor as code when no valid token

apiserver/poetry.lock, apiserver/pyproject.toml
=> build: update bkpaas-auth to version 2.0.5

apiserver/poetry.lock, apiserver/pyproject.toml
=> build: update bkpaas-auth to version 2.0.6

apiserver/paasng/paas_wl/cnative/specs/constants.py, apiserver/paasng/paas_wl/cnative/specs/entities.py, apiserver/paasng/paas_wl/networking/ingress/utils.py, apiserver/paasng/paas_wl/resources/base/exceptions.py, apiserver/paasng/paas_wl/resources/base/generation/v1.py, apiserver/paasng/paas_wl/resources/base/generation/v2.py, apiserver/paasng/paas_wl/resources/kube_res/base.py, apiserver/paasng/paas_wl/resources/kube_res/exceptions.py, apiserver/paasng/paas_wl/workloads/processes/controllers.py, apiserver/paasng/paas_wl/workloads/processes/drf_serializers.py, apiserver/paasng/paas_wl/workloads/processes/readers.py, apiserver/paasng/paas_wl/workloads/processes/serializers.py, apiserver/paasng/paas_wl/workloads/processes/urls.py, apiserver/paasng/paas_wl/workloads/processes/views.py, apiserver/paasng/paas_wl/workloads/processes/views_enduser.py, apiserver/paasng/paas_wl/workloads/processes/watch.py, apiserver/paasng/paasng/urls.py, apiserver/paasng/tests/paas_wl/resources/kube_res/test_base.py, apiserver/paasng/tests/paas_wl/workloads/processes/test_watch.py, operator/api/v1alpha2/constants.go, operator/pkg/controllers/resources/ingress_plugins.go, operator/pkg/controllers/resources/labels/labels.go, operator/pkg/platform/applications/info.go, operator/pkg/testing/bkapp.go
feature: 支持根据 namespace list-watch 进程状态
feature: 增加 list-watch 应用在指定环境下所有模块进程状态的API
enhance: 增加 bkapp.paas.bk.tencent.com/wl-app-name label 以快速查询与进程关联的 wl_app
refactor: 调整 list-watcher 接口返回格式, 将 slz 相关的逻辑后置到 views 层完成
=> feature: 支持根据 namespace list-watch 进程状态

webfe/package_vue/src/views/dev-center/app/services/instance.vue
=> fix: 国密展示方案，增强服务统一使用6个*展示

apiserver/paasng/paasng/publish/market/models.py, apiserver/paasng/paasng/publish/market/serializers.py, apiserver/paasng/paasng/publish/market/urls.py, apiserver/paasng/paasng/publish/market/utils.py, apiserver/paasng/paasng/publish/market/views.py, apiserver/paasng/tests/publish/market/test_utils.py, webfe/package_vue/src/store/modules/market.js, webfe/package_vue/src/views/dev-center/app/market/market-info.vue
refactor: 弱化 prefer_https 字段的作用(仅保留当 prefer_https is False 时回退 http 的…能力); 
refactor: 移除交互重构后不再使用的接口
=> refactor: 弱化 prefer_https 字段的作用; 移除交互重构后不再使用的接口

webfe/package_vue/src/views/dev-center/app/market/market-info.vue
=> fix: 切换应用访问地址编辑态bug修复

apiserver/paasng/paasng/plat_admin/system/serializers.py, apiserver/paasng/paasng/plat_admin/system/urls.py, apiserver/paasng/paasng/plat_admin/system/views.py, apiserver/paasng/tests/plat_admin/test_system.py
=> feat: add system api to list cluster and namespaces info by app 

apiserver/paasng/paasng/plat_admin/system/views.py
=> fix: use SYSAPI_READ_APPLICATIONS instead of SYSAPI_READ_SERVICES perm

apiserver/paasng/conf.yaml.tpl, apiserver/paasng/paasng/engine/configurations/config_var.py, apiserver/paasng/paasng/settings/__init__.py, apiserver/poetry.lock, apiserver/pyproject.toml
Fix:update blue-krill version (#634)
=> Fix:update blue-krill version (#634)

webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/visit-config.vue, webfe/package_vue/src/views/dev-center/app/market/market-info.vue, webfe/package_vue/src/views/dev-center/app/market/market-manager.vue, webfe/package_vue/src/views/dev-center/app/summary/default-overview.vue, webfe/package_vue/src/views/dev-center/app/summary/overview.scss
- 应用简介输入长度显示
- 未发布/为完善信息 访问地址编辑禁用，访问地址对齐
- 新建自定义IP编辑取消问题修复
- 应用开发-概览点击最近三天或者七天报错修复
=> Fix bug 1.2

apiserver/init.sh, apiserver/paasng/paasng/platform/modules/constants.py, apiserver/paasng/paasng/platform/modules/helpers.py
=> enhance: 支持通过 labels 过滤云原生应用的运行时镜像

webfe/package_vue/src/views/dev-center/app/engine/app-status/comps/process-event.vue, webfe/package_vue/src/views/dev-center/app/market/market-info.vue
=> fix: 云原生应用进程事件详情展示不全

apiserver/paasng/.importlinter
- Add import-linter config content for paas_wl module
=> Add import-linter config content for paas_wl module

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/index.vue
- https://github.com/huangpeng0428/bk-paas.git
=> fix: 云原生进程配置-容器端口删除报错修复

apiserver/paasng/paasng/extensions/declarative/deployment/svc_disc.py, apiserver/paasng/paasng/publish/entrance/preallocated.py, apiserver/paasng/tests/publish/entrance/test_preallocated.py
Enhance: make the result of svc-disc more accurate by get exposed_url_type first
=> Enhance: make the result of svc-disc more accurate by get exposed_url_type first

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue
=> bugfix: 修复 EventSource 未正常关闭则打开下一个 EventSource 的问题

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
=> fix: 创建应用扩缩容无需获取 Feature Flag

.pre-commit-config.yaml, apiserver/paasng/.importlinter, apiserver/poetry.lock, apiserver/pyproject.toml
- Add import-linter to pre-commit of apiserver directory
=> Add import-linter to pre-commit of apiserver directory

apiserver/paasng/tests/paas_wl/conftest.py
fix:fix the unit test after re-organize the modules
=> fix:fix the unit test after re-organize the modules

apiserver/paasng/paasng/platform/sourcectl/migrations/0011_mig_spec_cls.py
- Add migration script for the spec_cls attr of SourceTypeSpecConfig
=> Fix: add migration script for the spec_cls attr of SourceTypeSpecConfig

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue
- 云原生高级选项位置调整
- 代码分支获取报错时，需要将报错信息展示出来
=> Fix dev wmh

webfe/package_vue/src/store/modules/cloud-api.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/index.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/module-info.vue
=> fix: 进程配置编辑态下，镜像仓库添加编辑入口

apiserver/paasng/paas_wl/bk_app/processes/controllers.py, apiserver/paasng/tests/paas_wl/bk_app/processes/test_controllers.py, apiserver/paasng/tests/paas_wl/conftest.py
=> fix: Release 脏数据导致的进程查询失败问题

webfe/package_vue/src/views/dev-center/app/create-cloud-module/index.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
=> fix: 创建模块使用FeatureFlag属性错误

apiserver/paasng/paasng/platform/mgrlegacy/app_migrations/envs_base.py
=> fix: mypy static type check when run unit test

webfe/package_vue/src/components/app-quick-nav.vue
=> fix: 应用logo信息tooltips优化

apiserver/paasng/paasng/accessories/publish/sync_market/constant.py, apiserver/paasng/paasng/infras/legacydb/adaptors.py, apiserver/paasng/paasng/infras/legacydb/entities.py, apiserver/paasng/paasng/platform/mgrlegacy/app_migrations/envs_base.py, apiserver/paasng/tests/paasng/platform/mgrlegacy/test_envvar_migration.py
将类 EnvItem 挪动到合适的 entities.py 中
=> refactor: move class EnvItem to appropriate reference location(entities)

apiserver/paasng/paas_wl/workloads/processes/controllers.py, apiserver/paasng/paasng/dev_resources/sourcectl/git/client.py, apiserver/paasng/tests/paas_wl/conftest.py, apiserver/paasng/tests/paas_wl/workloads/processes/test_controllers.py, apiserver/paasng/tests/sourcectl/git/test_git_client.py
fix：
1. 超时时间默认改为：10分钟
- 暂时先不把这个配置放到配置项中
2. 分支名中特殊字符（/）导致展示不全
=> Release 1.3 branch fix

apiserver/paasng/paasng/platform/bkapp_model/importer/__init__.py, apiserver/paasng/paasng/platform/bkapp_model/importer/entities.py, apiserver/paasng/paasng/platform/bkapp_model/importer/env_vars.py, apiserver/paasng/paasng/platform/bkapp_model/importer/exceptions.py, apiserver/paasng/paasng/platform/bkapp_model/importer/importer.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/paasng/platform/engine/models/managers.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_env_vars.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_importer.py, apiserver/paasng/tests/paasng/platform/declarative/test_application.py, apiserver/paasng/tests/paasng/platform/engine/test_config_var.py
- Feature: allow import application manifest(only include the env vars)
=> Feature: allow import application manifest(only include the env vars)

apiserver/paasng/paasng/platform/modules/helpers.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/paasng/platform/modules/models/build_cfg.py, apiserver/paasng/paasng/platform/modules/serializers.py, apiserver/paasng/paasng/platform/modules/views.py, apiserver/paasng/tests/api/test_build_config.py
=> feature: BuildConfig API 支持保存仅镜像的配置信息

webfe/package_vue/src/components/authentication-info.vue
=> fix: 修复没有默认密钥导致显示不出应用密钥的bug

apiserver/paasng/paas_wl/bk_app/cnative/specs/crd/bk_app.py, apiserver/paasng/paas_wl/bk_app/cnative/specs/models/mount.py, apiserver/paasng/paasng/platform/bkapp_model/importer/entities.py, apiserver/paasng/paasng/platform/bkapp_model/importer/env_vars.py, apiserver/paasng/paasng/platform/bkapp_model/importer/importer.py, apiserver/paasng/paasng/platform/bkapp_model/importer/mounts.py, apiserver/paasng/paasng/platform/bkapp_model/importer/replicas.py, apiserver/paasng/paasng/platform/bkapp_model/importer/serializers.py, apiserver/paasng/paasng/platform/bkapp_model/manager.py, apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_env_vars.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_importer.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_mounts.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_replicas.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py
- Manifest importing support Mounts & envOverlay.replicas & manifest add replicas overlay
=> Manifest importing support Mounts & envOverlay.replicas & manifest add replicas overlay

apiserver/paasng/paasng/platform/applications/models.py, apiserver/paasng/tests/paasng/accessories/publish/entrance/test_preallocated.py
Fix exception when saas disc use a non-existent module name.
=> Fix exception when saas disc use a non-existent module name

apiserver/paasng/paas_wl/bk_app/deploy/management/commands/clean_timeout_pod.py
=> fix: use metadata.creationTimestamp instead of pod.status.startTime

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
- 镜像地址tag不能带 . 修复
- 镜像地址tag不能带 . 修复
=> bug：云原生体验bug修复

apiserver/paasng/paasng/platform/engine/models/config_var.py
=> fix: update environment_name for config_var not work

apiserver/paasng/paasng/platform/engine/workflow/protections.py, apiserver/paasng/paasng/platform/sourcectl/controllers/bare_git.py, apiserver/paasng/paasng/platform/sourcectl/git/client.py, apiserver/paasng/tests/paasng/platform/sourcectl/git/test_git_client.py
针对 raw git 的一些改进：
- 获取 branch/tag 的方法，由完成 clone 改为 blob-less clone
- 测试是否有访问权限的方法 touch()，由 bare clone 改为 ls-remote
- 少量 API 优化与调整
=> Misc enhancements on git client: list branches and touch operations speed up.

webfe/package_vue/static/json/paas_static.ce.js, webfe/package_vue/static/json/paas_static.ee.js
=> fix: 产品文档链接替换为环境变量

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/app-services.vue
=> fix: 增强服务使用指南间距问题修复

apiserver/paasng/paas_wl/bk_app/deploy/app_res/client.py, apiserver/paasng/paas_wl/bk_app/deploy/app_res/controllers.py, apiserver/paasng/paas_wl/bk_app/deploy/processes.py, apiserver/paasng/paas_wl/bk_app/processes/managers.py, apiserver/paasng/paas_wl/infras/resources/generation/version.py, apiserver/paasng/paasng/platform/engine/deploy/bg_build/utils.py, apiserver/paasng/tests/paas_wl/bk_app/deploy/app_res/test_client.py, apiserver/paasng/tests/paas_wl/infras/resources/generation/test_generation.py, apiserver/paasng/tests/paasng/platform/engine/deploy/bg_build/test_utils.py
- Fix SUB_PATH env var was overwritten after scale the process
- More infomation can be found in the code comments
=> Fix SUB_PATH env var was overwritten after scale the process

operator/api/v1alpha2/bkapp_types.go, operator/api/v1alpha2/bkapp_webhook_test.go, operator/pkg/controllers/resources/deployment.go, operator/pkg/controllers/resources/deployment_test.go, operator/pkg/controllers/resources/hooks.go, operator/pkg/controllers/resources/hooks_test.go, operator/pkg/utils/kubetypes/common.go, operator/pkg/utils/kubetypes/common_test.go
- Fix: $PORT in the command/args was not transformed to valid format
=> Fix: $PORT in the command/args was not transformed to valid format

apiserver/paasng/paasng/infras/legacydb/adaptors.py, apiserver/paasng/paasng/plat_admin/system/applications.py, apiserver/paasng/paasng/plat_admin/system/serializers.py, apiserver/paasng/paasng/plat_admin/system/views.py, apiserver/paasng/tests/paasng/plat_admin/test_system.py
enhance:uni_apps_list_minimal,uni_apps_query_by_id 添加查询参数
=> enhance:uni_apps_list_minimal,uni_apps_query_by_id 添加查询参数

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
=> fix: 将web进程默认置为第一个

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-env.vue
=> fix: 删除单个环境变量id获取代码优化

webfe/package_vue/src/components/app-quick-nav.vue
=> fix: 下拉导航域名样式间距问题修复

apiserver/paasng/paas_wl/workloads/networking/ingress/kres_entities/service.py
支持从云原生应用的 service labels 获取 service 对应的 process_type
=> feat: support view process service for cnative app

webfe/package_vue/src/views/dev-center/app/engine/log/access-log.vue, webfe/package_vue/src/views/dev-center/app/engine/log/custom-log.vue, webfe/package_vue/src/views/dev-center/app/engine/log/index.vue
- 云原生应用添加结构化日志
- 暂无可用日志时store默认值参数修复，Code Eslint
=> 云原生应用添加结构化日志

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/quota-popver/index.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process-creat.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
=> fix: 资源配额提示信息根据选择方案决定修复

apiserver/paasng/paas_wl/core/resource.py, apiserver/paasng/paas_wl/workloads/networking/ingress/views_enduser.py
=> feat: return process service by module for cnative app

webfe/package_vue/src/views/dev-center/app/create-cloud-module/index.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue
=> 托管方式、构建方式合并

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue, webfe/package_vue/src/views/dev-center/create-app/success-git.vue
- Dockerfile 应用创建去除模板参数，创建成功页无需展示git bash
- 镜像拉取策略tips方向调整
=> Dockerfile 应用创建去除模板参数，创建成功页无需展示git bash

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue
=> fix: 云原生扩缩容功能开放

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue
=> fix: 扩缩容弹窗展示

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/code-source.vue, webfe/package_vue/src/views/services/vcs/comps/svn.vue
=> fix: 修复snv弹窗提示和样式bug

webfe/package_vue/src/components/app-quick-nav.vue, webfe/package_vue/src/views/dev-center/app/create-cloud-module/index.scss, webfe/package_vue/src/views/dev-center/app/create-cloud-module/index.vue, webfe/package_vue/src/views/dev-center/create-app/success-git.scss, webfe/package_vue/src/views/dev-center/create-app/success-git.vue
- 创建模块去除模板参数
- 创建应用成功点击下载与gitbash对齐
- 应用过滤输入框字体不协调修复
- 创建模块-代码源不确实定时左对齐修复
- 创建应用成功-初始化模块使用新版样式
=> - 体验单据修复--创建模块-代码源不确实定时左对齐修复

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/scale-dialog.vue
=> fix: 扩缩容操作默认为default修复

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/app-services.vue
=> 未启用增强服务使用正常样式

apiserver/paasng/paas_wl/workloads/networking/ingress/kres_entities/service.py
回退代码：从 service 的 name 中获取 module 的兜底逻辑
=> revert: extract_process_type_from_name in ProcessServiceDeserializer

apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py
Fix: unable to start process using ${PORT:-5000}
=> Fix: unable to start process using ${PORT:-5000}

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/scale-dialog.vue
=> fix: 进程操作样式问题、云原生扩缩容自动调节默认禁用

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue
=> fix: 调整扩缩容后重新更新当前列表

operator/pkg/controllers/reconcilers/deploy_action.go, operator/pkg/controllers/reconcilers/deploy_action_test.go
- Operator: remove observed generation checking because updating annotation wont incr the value
=> Operator: remove observed generation checking because updating annotation wont incr the value

apiserver/paasng/paasng/misc/monitoring/monitor/alert_rules/config/app_rule.py, apiserver/paasng/paasng/misc/monitoring/monitor/alert_rules/config/constants.py, apiserver/paasng/paasng/misc/monitoring/monitor/alert_rules/config/entities.py, apiserver/paasng/paasng/misc/monitoring/monitor/alert_rules/config/metric_label.py, apiserver/paasng/paasng/misc/monitoring/monitor/serializers.py, apiserver/paasng/tests/paasng/misc/monitoring/alert_rules/conftest.py
=> fix: cnative app alert rules missing namespace

apiserver/paasng/paasng/infras/bkmonitorv3/params.py, apiserver/paasng/paasng/misc/monitoring/monitor/serializers.py, apiserver/paasng/tests/api/test_monitor.py, apiserver/paasng/tests/utils/mocks/bkmonitor.py
=> feat:监控告警记录添加 env 字段

webfe/package_vue/src/main.js, webfe/package_vue/src/store/modules/alarm.js, webfe/package_vue/src/views/dev-center/app/engine/monitor-alarm/alarm-record.vue, webfe/package_vue/src/views/dev-center/app/engine/monitor-alarm/index.vue
=> 告警记录页面修改，添加蓝鲸监控记录

webfe/package_vue/src/views/dev-center/create-app/success-git.vue
=> fix: 创建成功页面模块地址文案bug修复

webfe/package_vue/src/views/dev-center/app/engine/monitor-alarm/alarm-record.vue
=> fix: 告警记录-告警名称宽度调整

apiserver/paasng/paas_wl/utils/kubestatus.py, apiserver/paasng/paasng/platform/sourcectl/connector.py
Extend the expires of the source template which generated after app creation  to 4 hours
=> Extend the expires of the downloadable address of the source template to 4 hours

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/observability-config/alarm-strategy.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/observability-config/index.vue, webfe/package_vue/src/views/dev-center/app/engine/monitor-alarm/alarm-record.vue
=> fix: 告警策略未部署处理

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/image-credential/index.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/module-info.vue, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue
- 进程管理-切换时间去除弹窗规范
- 镜像凭证操作后，基本信息更新镜像凭证列表
=> 进程管理-切换时间去除弹窗规范、镜像凭证操作后，基本信息更新镜像凭证列表

apiserver/paasng/paas_wl/bk_app/processes/kres_entities.py, apiserver/paasng/paas_wl/bk_app/processes/kres_slzs.py, apiserver/paasng/paas_wl/infras/resources/base/kres.py, apiserver/paasng/tests/paas_wl/bk_app/processes/test_managers.py, apiserver/paasng/tests/paas_wl/test_utils/test_kubestatus.py, apiserver/paasng/tests/paas_wl/utils/basic.py
Feature: add "rich_status" field on proc instance.
=> Feature: add "rich_status" field on proc instance.

apiserver/paasng/paas_wl/bk_app/cnative/specs/views_enduser.py, apiserver/paasng/paas_wl/bk_app/processes/views.py
=> feat: list cnative process instances by deployment_id

apiserver/paasng/paas_wl/bk_app/processes/views.py
=> fix: list cnative instances with null bkapp_release_id

apiserver/paasng/paas_wl/bk_app/processes/serializers.py
- Return rich_status field in API resp.
=> Return rich_status field in API resp.

apiserver/paasng/paas_wl/bk_app/cnative/specs/procs/replicas.py, apiserver/paasng/paas_wl/bk_app/deploy/processes.py, apiserver/paasng/paas_wl/infras/cluster/models.py, apiserver/paasng/paas_wl/workloads/autoscaling/constants.py, apiserver/paasng/paas_wl/workloads/autoscaling/entities.py, apiserver/paasng/paas_wl/workloads/autoscaling/kres_entities.py, apiserver/paasng/paas_wl/workloads/autoscaling/kres_slzs.py, apiserver/paasng/paasng/platform/bkapp_model/importer/env_overlays.py, apiserver/paasng/paasng/platform/bkapp_model/importer/processes.py, apiserver/paasng/paasng/platform/bkapp_model/management/commands/sanitize_autoscaling.py, apiserver/paasng/paasng/platform/bkapp_model/manager.py, apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/bkapp_model/serializers.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/tests/api/test_bkapp_model.py, apiserver/paasng/tests/paas_wl/bk_app/cnative/specs/conftest.py, apiserver/paasng/tests/paas_wl/bk_app/cnative/specs/crd/bkapp_v1.yaml, apiserver/paasng/tests/paas_wl/bk_app/cnative/specs/procs/test_replicas.py, apiserver/paasng/tests/paas_wl/bk_app/cnative/specs/test_resource.py, apiserver/paasng/tests/paas_wl/bk_app/cnative/specs/test_svc_disc.py, apiserver/paasng/tests/paas_wl/bk_app/deploy/test_processes.py, apiserver/paasng/tests/paas_wl/workloads/autoscaling/test_serializers.py, apiserver/paasng/tests/paas_wl/workloads/networking/egress/test_region.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_env_overlays.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_importer.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manager.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py
- Feature: add autoscaling support for the process managing API of cnative app
- Add more tests for `CNativeProcController` class & fix some failing tests
=> Feature: add autoscaling support for the process managing API of cnative app

webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/components/searching/searchAppList.vue, webfe/package_vue/src/views/dev-center/app/basic-config/info.vue, webfe/package_vue/src/views/dev-center/app/basic-config/visit-url/index.vue, webfe/package_vue/src/views/dev-center/app/create-cloud-module/index.vue, webfe/package_vue/src/views/dev-center/app/create-module/index.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-history.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-module-list.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/scale-dialog.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/code-source.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/mirror.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-env.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue, webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/visit-config.vue, webfe/package_vue/src/views/dev-center/app/engine/env-vars/index.vue, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue, webfe/package_vue/src/views/dev-center/app/market/market-info.vue, webfe/package_vue/src/views/dev-center/app/market/market-manager.vue, webfe/package_vue/src/views/dev-center/migration/index.vue, webfe/package_vue/src/views/plugin-center/create-plugin/index.vue
- 错误弹窗优先展示接口返回的 detail 字段
- eslint
- 云原生-部署管理版本、分支信息区分修复
- 应用列表无数据字体大小调整
=> fix: 接口错误detail字段优先展示、体验问题修复

apiserver/paasng/paas_wl/bk_app/cnative/specs/serializers.py, apiserver/paasng/paasng/platform/engine/deploy/version.py
=> fix: parse build.image from deprecated json_value

apiserver/paasng/paas_wl/bk_app/processes/serializers.py
- Add "policy" on ScalingConfigSLZ
=> Add "policy" on ScalingConfigSLZ

apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/engine/configurations/config_var.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py
=> feat: inject envs for cloud-native app on the paasng(apiserver) side

apiserver/paasng/paasng/platform/engine/deploy/version.py
=> fix: no build.image in V1ALPHA1

apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/accountmgr/user_profile_list.html
Fix: undefined exception in admin page "admin/accountmgr/"
=> Fix: undefined exception in admin page "admin/accountmgr/"

webfe/package_vue/src/views/dev-center/app/create-cloud-module/index.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-hook.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue
=> feat: 创建应用、创建模块调整

apiserver/paasng/paas_wl/infras/resources/base/kube_client.py, apiserver/paasng/paas_wl/workloads/networking/ingress/kres_entities/ingress.py
- Fix: unsafe fix done by ruff (remove .keys())
=> Fix: unsafe fix done by ruff (remove .keys())

apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/tests/api/test_modules.py
-  修复 hook 参数取错的问题
-  添加对应有效单测
=> fix: missing hook params

apiserver/paasng/paasng/misc/metrics/workloads/deployment.py
一个 unavailable_deployments 指标，不应该导致整个 metrics 服务崩溃
=> fix:修复 django metrics 接口

operator/main.go, operator/pkg/metrics/registry.go
TODO: remove extra metrics listener
=> refactor: register custom metrics to kubebuilder default register

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
=> 进程配置-无web进程正常展示

apiserver/paasng/paas_wl/bk_app/deploy/app_res/controllers.py, apiserver/paasng/paas_wl/infras/resources/base/kres.py, apiserver/paasng/paas_wl/utils/constants.py, apiserver/paasng/paasng/platform/engine/deploy/bg_command/bkapp_hook.py, apiserver/paasng/paasng/platform/engine/deploy/bg_command/tasks.py, apiserver/paasng/paasng/platform/engine/deploy/release/operator.py, apiserver/paasng/paasng/platform/engine/migrations/0017_reset_step_meta_set.py, apiserver/paasng/paasng/platform/engine/phases_steps/steps.py, apiserver/paasng/paasng/platform/engine/utils/output.py, apiserver/paasng/paasng/platform/engine/workflow/flow.py, apiserver/paasng/tests/paas_wl/infras/resources/base/test_kres.py, apiserver/paasng/tests/paasng/platform/engine/deploy/test_bkapp_hook.py
新增：支持云原生应用部署时查看 pre-release hook 标准输出日志
=> feat: view bkapp hook logs on deploying

apiserver/paasng/paasng/platform/bkapp_model/importer/importer.py, apiserver/paasng/paasng/platform/bkapp_model/importer/processes.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_processes.py
=> feat: add import image_credential_name in import_processes logic

webfe/package_vue/src/views/dev-center/app/summary/default-overview.vue
=> fix: 概览-告警数量: 应该使用告警记录页面一样的 API

webfe/package_vue/src/components/uploader/index.vue
=> S-mart包上传报错修复

operator/main.go
- 设置 zap  Development 默认为 false
=> refactor: set zap Development to false

builder-stack/heroku-buildpacks/bk-buildpack-go/Makefile, builder-stack/heroku-buildpacks/bk-buildpack-go/README.md, builder-stack/heroku-buildpacks/bk-buildpack-go/patchs/buildpack/files.json.patch
=> feat: patch go1.21.4.linux-amd64.tar.gz to files.json

apiserver/paasng/paas_wl/bk_app/cnative/specs/management/commands/store_bkapp_to_db.py
dry_run 执行 store_bkapp_to_db 命令时校验 json_value, 提前发现无法迁移数据的应用(如环境变量冲突)
=> feat: add validate json_value when dry run store_bkapp_to_db command

apiserver/paasng/paas_wl/bk_app/cnative/specs/resource.py, operator/api/v1alpha2/bkapp_webhook.go, operator/api/v1alpha2/bkapp_webhook_test.go
移除 apiserver 和 operator 中对一个模块必须有 web 进程的限定
=> refactor: remove constraint for module to have a web process

apiserver/paasng/paasng/platform/engine/deploy/building.py, apiserver/paasng/paasng/settings/workloads.py, builder-stack/kaniko-shim/cmd/launcher/main.go
新增配置对应环境变量: PAAS_WL_KANIKO_REGISTRY_MIRRORS
=> enhance: 支持设置镜像源代理

apiserver/paasng/paasng/bk_plugins/bk_plugins/logging.py, apiserver/paasng/paasng/utils/es_log/search.py, apiserver/paasng/tests/api/apigw/test_log.py
Use ascend order for quering plugin logs.
=> Use ascend order for quering plugin logs.

apiserver/paasng/paas_wl/apis/admin/serializers/logs.py, apiserver/paasng/paas_wl/apis/admin/urls.py, apiserver/paasng/paas_wl/apis/admin/views/logs.py, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/applications/detail/base.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/applications/detail/engine/log_config.html, apiserver/paasng/paasng/plat_admin/admin42/urls.py, apiserver/paasng/paasng/plat_admin/admin42/views/applications.py, apiserver/paasng/paasng/plat_admin/admin42/views/engine/log_config.py
用于灰度停止双采，部分应用停止双采一段时间无异常后，再批量全部停止日志双采。
=> feature: admin 新增控制某个环境是否挂载日志到宿主机的功能

webfe/package_vue/src/views/plugin-center/plugin/version-manager/index.vue
=> fix: 插件访问入口按钮，接口400弹窗提示改为禁用tips

apiserver/paasng/paasng/platform/engine/management/commands/sync_step_meta_set.py
=> fix: default slug-pilot step already exists

apiserver/paasng/paas_wl/bk_app/deploy/actions/archive.py, apiserver/paasng/paas_wl/bk_app/deploy/processes.py, apiserver/paasng/paas_wl/bk_app/processes/exceptions.py, apiserver/paasng/paasng/plat_admin/admin_cli/apps.py, apiserver/paasng/paasng/plat_admin/admin_cli/cmd_utils.py, apiserver/paasng/paasng/plat_admin/admin_cli/management/commands/adm_archive.py, apiserver/paasng/paasng/plat_admin/admin_cli/management/commands/adm_stats.py, apiserver/paasng/paasng/plat_admin/admin_cli/mapper_version.py, apiserver/paasng/paasng/settings/__init__.py, apiserver/paasng/tests/paas_wl/bk_app/processes/test_exceptions.py, apiserver/paasng/tests/paasng/plat_admin/admin_cli/test_mapper_version.py
- Add "admin_cli" module with 2 new commands: "adm_stats", "adm_archive"
- "adm_stats": viewing platform and application stats
- "adm_archive": archive applications
- Enhance: consider an archive process as successful when the namespace can not be found
=> Add "admin_cli" module with 2 new commands: "adm_stats", "adm_archive"

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/app-perm.vue, webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/render-list.vue
=> fix: 云API权限批量申请续期操作问题修复

apiserver/paasng/paas_wl/bk_app/processes/models.py, apiserver/paasng/paas_wl/bk_app/processes/views_enduser.py, apiserver/paasng/paasng/infras/oauth2/api.py, apiserver/paasng/paasng/platform/bkapp_model/manager.py, apiserver/paasng/paasng/platform/declarative/deployment/controller.py
=> fix: not sync target_replicas from desc by env

apiserver/paasng/paas_wl/bk_app/deploy/app_res/controllers.py, apiserver/paasng/paasng/plat_admin/admin_cli/deploy.py, apiserver/paasng/paasng/plat_admin/admin_cli/management/commands/adm_mapper_v1.py, apiserver/paasng/paasng/plat_admin/admin_cli/management/commands/adm_stats.py
- Add "adm_mapper_v1" command, it helps applications that using resource mapper v1 migrate to v2.
=> Add "adm_mapper_v1" command

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/scale-dialog.vue
=> feat: 切换了扩缩容方式立刻触发list

apiserver/paasng/paasng/platform/engine/management/commands/sync_step_meta_set.py
=> fix: delete is_default=True old dirty step meta data

apiserver/paasng/tests/paasng/platform/bkapp_model/test_manager.py
=> test: fix test_set_replicas_integrated

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-build.vue
=> fix: 初始化模板，根据构建方式展示

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/app-perm.vue
=> - 云api权限过期无法续期，添加申请操作

apiserver/paasng/paasng/platform/bkapp_model/constants.py, apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/declarative/handlers.py, apiserver/paasng/paasng/platform/engine/deploy/image_release.py
=> fix: missing 'bash /runner/init' prefix in scripts for s-mart app

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/app-perm.vue
Reverts TencentBlueKing/blueking-paas#1047
=> Revert "- 云api权限过期无法续期，添加申请操作"

apiserver/poetry.lock, apiserver/pyproject.toml
=> build: update bkpaas-auth to 2.0.7

apiserver/poetry.lock, apiserver/pyproject.toml
=> build: update bkpaas-auth to 2.0.8

apiserver/paasng/paas_wl/bk_app/processes/models.py
=> fix: not update process target_status to start when deploy

apiserver/paasng/paas_wl/bk_app/applications/api.py, apiserver/paasng/tests/paas_wl/bk_app/applications/test_api.py, apiserver/paasng/tests/utils/helpers.py
- Enhance: update type when engine app already exists.
=> Enhance: update type when engine app already exists.

webfe/package_vue/package.json, webfe/package_vue/src/App.vue, webfe/package_vue/src/assets/css/pages/overview.scss, webfe/package_vue/src/assets/css/ps-style.scss, webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/main.js, webfe/package_vue/src/store/index.js, webfe/package_vue/src/views/dev-center/app/index.vue, webfe/package_vue/src/views/dev-center/index.vue, webfe/package_vue/src/views/dev-center/search/index.vue, webfe/package_vue/src/views/plugin-center/plugin/index.vue, webfe/package_vue/src/views/services/base.vue
=> feat: 开发者中心接入通知中心

webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/visit-config.vue
=> fix：添加自定义域名时，填写域名直接提交报错修复

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/index.vue
=> fix: 创建令牌弹窗其他方式关闭状态重置

apiserver/paasng/paas_wl/bk_app/cnative/specs/image_parser.py, apiserver/paasng/paas_wl/bk_app/cnative/specs/views_enduser.py, apiserver/paasng/paasng/platform/bkapp_model/importer/build.py, apiserver/paasng/paasng/platform/sourcectl/controllers/docker.py, apiserver/paasng/paasng/settings/__init__.py, apiserver/poetry.lock, apiserver/pyproject.toml
主要是 moby-distribution 这 SDK 引入缓存参数
=> enhance: 设置 list tags 超时

apiserver/paasng/paasng/plat_admin/system/applications.py, apiserver/paasng/paasng/plat_admin/system/serializers.py, apiserver/paasng/paasng/plat_admin/system/views.py, apiserver/paasng/paasng/platform/applications/operators.py, apiserver/paasng/tests/paasng/plat_admin/test_system.py
- 优化前 SQL 查询次数：6 + 2n(应用开发者) + 4n(联系人)
- 优化后 SQL 查询次数：6 + 2n(应用开发者) + 5(联系人)
测试：10 个应用：
- 优化前：耗时：`9.8s`，调用 SQL `66` 次
- 优化后（查询参数不变）：耗时 6.36s ，调用 SQL 31 次
- 优化后（只查询基本信息）：耗时：`370.17ms`，调用 SQL : `7` 次
- 添加参数：&include_developer_info=False&include_contact_info=False
=> feat: 优化 query_by_id API

webfe/package_vue/bk.config.js
- Enhance: the "enable-HTTPS" related logic is not complete webfe dev-server
=> Enhance: the "enable-HTTPS" related logic is not complete webfe dev-server

webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/visit-config.vue
- 访问管理：有滚动条时，最后一个模块没有操作按钮，导致无法添加修改域名信息
=> fix: 访问管理：有滚动条时，最后一个模块没有操作按钮，导致无法添加修改域名信息

bkpaas-cli/pkg/handler/deploy.go
Reverts TencentBlueKing/blueking-paas#1138
=> Revert "fix: bkpaas-cli 暂停使用云原生相关接口"

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue
=> fix: 云原生部署管理，bk-svn 查看代码差异功能不正常

webfe/package_vue/package.json, webfe/package_vue/src/views/dev-center/app/basic-config/info.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-history.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/code-source.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/mirror.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-build.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-network/config-item.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-volume.vue, webfe/package_vue/src/views/dev-center/app/engine/packages/index.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue, webfe/package_vue/src/views/dev-center/create-app/external.vue, webfe/package_vue/src/views/dev-center/create-app/main.vue
- 通知中心前端组件升级
- 云原生应用-部署历史：可直接点击表格内容触发查看日志操作
- 模块配置-更多配置-服务发现报错bug修复
- 模块配置-->挂载卷侧边栏编辑规范
=> 通知中心前端组件升级、体验问题修复

webfe/package_vue/src/store/modules/base-info.js, webfe/package_vue/src/store/modules/credential.js, webfe/package_vue/src/store/modules/entry-config.js, webfe/package_vue/src/store/modules/processes.js, webfe/package_vue/src/views/dev-center/app/basic-config/access-portal/domain.vue, webfe/package_vue/src/views/dev-center/app/basic-config/visit-url/index.vue, webfe/package_vue/src/views/dev-center/app/engine/app-status/comps/process-operation.vue, webfe/package_vue/src/views/dev-center/app/engine/deployment/comps/deploy-action/index.vue, webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/custom-domain.vue, webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/visit-config.vue, webfe/package_vue/src/views/dev-center/app/engine/processes/comps/process-operation.vue
- 去除后端 API 中的  /svc_workloads/ 前缀
- 代码格式化
=> fix: 去除后端 API 中的  /svc_workloads/ 前缀

webfe/package_vue/src/App.vue
=> bug: 解决插件开发者中心滚动条问题

builder-stack/cnb-builder-shim/cmd/dev-entrypoint/main.go
=> fix: use incorrect err var

webfe/package_vue/src/components/create-persistent-storage-dailog.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-volume.vue
=> bug: 持久存储编辑无法保存，字号调整

apiserver/paasng/.importlinter, apiserver/paasng/paasng/accessories/log/client.py, apiserver/paasng/paasng/accessories/log/shim/bklog_custom_collector_config.py, apiserver/paasng/paasng/accessories/log/views/config.py, apiserver/paasng/paasng/infras/bk_log/backend/apigw.py, apiserver/paasng/paasng/infras/bk_log/backend/esb.py, apiserver/paasng/paasng/infras/bk_log/client.py, apiserver/paasng/tests/paasng/infras/bk_log/test_client.py, bkpkg-bkpaas3.yaml
这个 PR 只对接了查询接口，还没有把查询的流程串过去（大概率要加配置，反正下个PR弄就对了）
=> 对接日志平台查询接口

webfe/package_vue/src/views/plugin-center/create-plugin/index.vue, webfe/package_vue/src/views/plugin-center/create-plugin/success.vue
=> fix: codecc-325 体验问题

apiserver/paasng/paasng/platform/applications/serializers/app.py, apiserver/paasng/paasng/platform/applications/views.py
=> feat: 修改应用名称时可同时修改应用 LOGO

webfe/package_vue/src/views/dev-center/app/basic-config/index.vue
=> 普通应用：应用配置不展示持久存储 tab

apiserver/paasng/paasng/accessories/publish/sync_market/engine.py, apiserver/paasng/paasng/accessories/publish/sync_market/handlers.py
- Fix: Product info sync sometimes failed due to missing MobileConfig object
=> Fix: Product info sync sometimes failed due to missing MobileConfig object

apiserver/paasng/paasng/bk_plugins/bk_plugins/serializers.py, apiserver/paasng/paasng/bk_plugins/bk_plugins/views.py
=> feat: 修改插件基本信息时可同时修改插件使用方

apiserver/paasng/paas_wl/workloads/networking/entrance/shim.py, apiserver/paasng/paas_wl/workloads/networking/entrance/views.py, apiserver/paasng/paasng/accessories/ci/exceptions.py, apiserver/paasng/paasng/accessories/ci/handlers.py, apiserver/paasng/paasng/platform/engine/deploy/building.py
- Enhance: remove unnecessary exception logging in ci.handler and deploy.building.
=> Enhance: remove unnecessary exception logging in ci.handler and deploy.building.

webfe/package_vue/src/App.vue, webfe/package_vue/static/login_success.html
=> fix: 登录弹框用 windows.open 打开

webfe/package_vue/src/components/deploy/deploy-log-sideslider.vue, webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/render-list.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue, webfe/package_vue/src/views/dev-center/app/engine/log/access-log.vue
- 云API管理-云API权限-组件API-检查搜索框多个API搜索，多api搜索结果展示优化
=> fix: 云API管理-云API权限-组件API-检查搜索框多个API搜索，多api搜索结果展示优化

apiserver/paasng/paasng/platform/applications/constants.py, apiserver/paasng/paasng/platform/applications/views.py
=> feat: 应用列表API添加我创建的应用个数

apiserver/paasng/paasng/accessories/publish/market/models.py, apiserver/paasng/paasng/accessories/publish/market/status.py, apiserver/paasng/paasng/accessories/publish/sync_market/handlers.py, apiserver/paasng/paasng/platform/applications/models.py, apiserver/paasng/paasng/platform/engine/workflow/flow.py, apiserver/paasng/tests/api/test_market_config.py, apiserver/paasng/tests/paasng/accessories/publish/test_entrance.py
- Fix: an archived application failed to publish to market automatically after the prod environment has been bring back online
- Replace the event handler for Deployment model with a function to make the code more explicit
=> Fix: an archived application failed to publish to market automatically after the prod environment has been bring back online

webfe/package_vue/src/store/modules/plugin.js, webfe/package_vue/src/views/dev-center/app/basic-config/plugin-info.vue
=> bug: 插件开发者中心：插件使用方无法选择查看

apiserver/paasng/paasng/platform/engine/workflow/flow.py
- Fix: the web client might get obsolete released info because the release phase ended too early
- More details can be found in the code comments.
=> Fix: the web client might get obsolete released info because the release phase ended too early

builder-stack/cloudnative-buildpacks/builders/heroku-builder/heroku-18.toml, builder-stack/cloudnative-buildpacks/builders/heroku-builder/heroku-22.toml, builder-stack/cnb-builder-shim/cmd/build-init/main.go, builder-stack/cnb-builder-shim/cmd/lifecycle-driver/main.go, builder-stack/cnb-builder-shim/pkg/dockercreds/access_checker.go
=> feature: use fock lifecycle which can skip verify self-signed certificaitons

webfe/package_vue/src/views/dev-center/app/summary/default-overview.vue
=> fix：主模块没有运行中的进程，导致资源指标不展示

apiserver/paasng/paasng/platform/mgrlegacy/tasks.py
=> fix: convert ReturnList to list for cattr.unstructure

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/app-perm.vue
- 云API权限已申请权限本地筛选修复v1.2，多筛选体验修复
=> fix: 云API权限已申请权限本地筛选修复v1.2

apiserver/paasng/paasng/platform/mgrlegacy/cnative_migrations/application.py, apiserver/paasng/paasng/platform/mgrlegacy/cnative_migrations/cluster.py, apiserver/paasng/paasng/platform/mgrlegacy/cnative_migrations/wl_app.py, apiserver/paasng/paasng/platform/mgrlegacy/task_data.py, apiserver/paasng/paasng/platform/mgrlegacy/views.py, apiserver/paasng/tests/paasng/platform/mgrlegacy/cnative/test_migrate.py, apiserver/paasng/tests/paasng/platform/mgrlegacy/cnative/test_migrators.py
=> fix: model_to_dict need instance not uuid when ForeignKey

webfe/package_vue/src/assets/css/ps-style.scss, webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/views/dev-center/app/basic-config/plugin-info.vue, webfe/package_vue/src/views/dev-center/app/engine/log/access-log.vue, webfe/package_vue/src/views/dev-center/app/engine/log/custom-log.vue, webfe/package_vue/src/views/dev-center/index.vue, webfe/package_vue/src/views/plugin-center/plugin/index.vue, webfe/package_vue/src/views/services/vcs/comps/svn.vue
- 导航条在 1366px 宽度下显示不全修复
- 去除全局样式影响下页面展示不全问题
- 基本信息：插件使用方为空是需要传参数
=> fix：导航条在 1366px 宽度下显示不全修复，去除全局样式影响下页面展示不全问题，其他修复项

webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/store/modules/service.js, webfe/package_vue/src/views/dev-center/app/services/instance.vue, webfe/package_vue/src/views/dev-center/index.vue, webfe/package_vue/static/json/paas_static.ce.js, webfe/package_vue/static/json/paas_static.ee.js
=> fix: 社区版导航乱链接错误修复

webfe/package_vue/src/views/dev-center/create-app/success-simple.vue
=> fix: 外链应用创建成功引导页英文单词前缀去除

apiserver/paasng/support-files/apigw/api_doc/en/create_module.md, apiserver/paasng/support-files/apigw/api_doc/en/import_manifest.md, apiserver/paasng/support-files/apigw/api_doc/en/retrieve_applications_info_by_db_name.md, apiserver/paasng/support-files/apigw/api_doc/zh/create_module.md, apiserver/paasng/support-files/apigw/api_doc/zh/import_manifest.md, apiserver/paasng/support-files/apigw/api_doc/zh/retrieve_applications_info_by_db_name.md, apiserver/paasng/support-files/apigw/definition.yaml, apiserver/paasng/support-files/apigw/resources.yaml
- API 网关上所有 API 都设置为需要校验应用权限
- 添加 3 个文档:import_manifest；create_module；retrieve_applications_info_by_db_name
=> feat: API 网关上所有 API 都设置为需要校验应用权限

webfe/package_vue/src/components/paas-header.vue
- 点击右上角退出登录的时候，需要添加参数 is_from_logout=1
=> feat: 点击右上角退出登录的时候，需要添加参数 is_from_logout=1

webfe/package_vue/src/components/paas-header.vue
- 退出登录对c_url组成部分进行编码，删除logout函数
=> fix: 退出登录对c_url组成部分进行编码，删除logout函数

cloudnative-buildpacks/builders/heroku-builder/heroku-18.toml, cloudnative-buildpacks/builders/heroku-builder/heroku-22.toml, cloudnative-buildpacks/buildpacks/bk-buildpack-go/Makefile, cloudnative-buildpacks/buildpacks/bk-buildpack-go/cnb-buildpack/buildpack.toml, heroku-buildpacks/bk-buildpack-go/Makefile, heroku-buildpacks/bk-buildpack-go/patchs/buildpack/bin/compile.patch, heroku-buildpacks/bk-buildpack-go/patchs/buildpack/files.json.patch
=> feat: update bk-buildpack-go to v191

webfe/package_vue/src/views/dev-center/app/basic-config/plugin-info.vue, webfe/package_vue/src/views/dev-center/create-app/success-smart.vue, webfe/package_vue/src/views/dev-center/index.vue
- 插件信息描述添加
- 应用搜索点击iocn搜索后，清空搜索框操作无法触发搜索行为修复
- smart应用新建部署，跳转页面错误修复
=> fix: 测试提单修复

webfe/package_vue/src/views/dev-center/app/basic-config/plugin-info.vue, webfe/package_vue/src/views/dev-center/create-app/success-smart.vue, webfe/package_vue/src/views/dev-center/index.vue
- 插件信息描述添加
- 应用搜索点击iocn搜索后，清空搜索框操作无法触发搜索行为修复
- smart应用新建部署，跳转页面错误修复
=> fix: 体验提单修复

webfe/package_vue/src/views/dev-center/app/engine/deployment/comps/deploy-action/index.vue
- 下拉分支接口调整，新增display_type 用户展示
=> update: 下拉分支接口调整，新增display_type 用户展示

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue
- 云原生部署管理下拉分支接口调整，新增display_type 用户展示
=> update: 云原生部署管理下拉分支接口调整，新增display_type 用户展示

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue
=> chore(cherry-pick): use display_type as displayName when deploy

webfe/package_vue/package.json
=> update: 通知中心更新

apiserver/paasng/paasng/platform/bkapp_model/utils.py, apiserver/paasng/paasng/platform/engine/configurations/image.py, apiserver/paasng/paasng/platform/engine/deploy/image_release.py, apiserver/paasng/paasng/platform/engine/processes/views.py
- enhance: improve some of the s-mart app checking statements
=> enhance: improve some of the s-mart app checking statements

apiserver/paasng/paasng/platform/smart_app/services/dispatch.py, apiserver/paasng/paasng/platform/sourcectl/controllers/package.py, apiserver/paasng/paasng/platform/sourcectl/models.py, apiserver/paasng/paasng/platform/sourcectl/serializers.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/test_controller.py
- enhance: save the original file name as "package_name" when uploading s-mart package
- TODO: Verify the impact of this PR to lesscode package uploading
=> enhance: save the original file name as "package_name" when uploading s-mart package

apiserver/paasng/tests/api/apigw/test_system_apis.py, apiserver/paasng/tests/api/test_engine.py, apiserver/paasng/tests/paas_wl/bk_app/processes/test_managers.py, apiserver/paasng/tests/paasng/accessories/publish/market/test_publish.py, apiserver/paasng/tests/paasng/accessories/servicehub/test_manager.py, apiserver/paasng/tests/paasng/accessories/services/test_utils.py, apiserver/paasng/tests/paasng/infras/accounts/test_middlewares.py, apiserver/paasng/tests/paasng/infras/accounts/test_models.py, apiserver/paasng/tests/paasng/misc/monitoring/metrics/test_client.py, apiserver/paasng/tests/paasng/platform/applications/test_applications.py, apiserver/paasng/tests/paasng/platform/engine/test_config_var.py, apiserver/paasng/tests/paasng/platform/mgrlegacy/test_envvar_migration.py, apiserver/paasng/tests/paasng/platform/mgrlegacy/test_migration.py, apiserver/paasng/tests/paasng/test_utils/test_validators.py, apiserver/paasng/tests/utils/helpers.py
- enhance: refactor unittest style tests to pytest style
=> enhance: refactor "unittest" style tests to "pytest" style

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue
=> fix: 云原生进程副本数展示错误修复

apiserver/paasng/paasng/platform/mgrlegacy/utils.py
=> fix: raise Cluster.DoesNotExist in func get_cnative_target_cluster

apiserver/paasng/paasng/platform/smart_app/services/detector.py, apiserver/paasng/paasng/platform/sourcectl/package/client.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/test_client.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/test_controller.py
- enhance: improve the error message when uploading a corrput package
=> enhance: improve the error message when uploading a corrput package

webfe/package_vue/src/store/modules/migration.js, webfe/package_vue/src/views/dev-center/app/engine/app-migration-info/index.vue, webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/visit-config.vue
=> fix: 迁移信息访问地址更替接口地址

apiserver/init.sh, apiserver/paasng/conf.yaml.tpl, apiserver/paasng/paasng/platform/modules/management/commands/manage_image.py, apiserver/paasng/paasng/platform/modules/management/commands/push_smart_image.py, apiserver/paasng/paasng/settings/__init__.py
- 调整与修复 init.sh，以支持 cnb 镜像
- 调整 SMART_IMAGE_TAG 和 SMART_CNB_IMAGE_TAG，保持与云原生普通应用语义版本一致
=> feat: add push cnb image

apiserver/init.sh, apiserver/paasng/conf.yaml.tpl, apiserver/paasng/paasng/platform/modules/management/commands/manage_image.py, apiserver/paasng/paasng/platform/modules/management/commands/push_smart_image.py, apiserver/paasng/paasng/settings/__init__.py
cherry pick 4f3128ab0e6d59ff7fe1d149843ec38dcc333003
=> chore: feat: add push cnb image

apiserver/paasng/paasng/platform/applications/serializers/__init__.py, apiserver/paasng/paasng/platform/applications/serializers/fields.py, apiserver/paasng/paasng/platform/declarative/application/validations/v2.py, apiserver/paasng/paasng/platform/declarative/application/validations/v3.py, apiserver/paasng/paasng/platform/declarative/serializers.py, apiserver/paasng/tests/paasng/platform/applications/test_serializers.py
- refactor: clean code for AppIDField
=> refactor: clean code for AppIDField

apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/applications/detail/overview.html, apiserver/paasng/paasng/plat_admin/admin42/views/applications.py
- feat: add a visit link to the admin application detail page for convenience.
=> feat: add a visit link to the admin application detail page

apiserver/paasng/paasng/platform/mgrlegacy/tasks.py
=> fix: missing sync_external_url_to_market after confirm app migration

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/code-source.vue
=> update: 变更features

apiserver/paasng/paasng/platform/declarative/application/validations/v3.py, apiserver/paasng/paasng/platform/declarative/handlers.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v3/test_app.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v3/test_deployment.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v3/test_probes.py, apiserver/paasng/tests/paasng/platform/declarative/utils.py, apiserver/paasng/tests/paasng/platform/smart_app/assets/cnb-image/app_desc.yaml
=> refactor: use camel case in specVersion:3(app_desc.yaml)

webfe/package_vue/src/components/paas-cloud-app-nav.vue, webfe/package_vue/src/views/dev-center/app/index.vue, webfe/package_vue/src/views/dev-center/index.vue
=> fix: 通过接口标记控制云原生迁移功能是否显示

webfe/package_vue/src/App.vue, webfe/package_vue/src/components/paas-footer.vue, webfe/package_vue/src/router/index.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-env.vue, webfe/package_vue/src/views/dev-center/app/engine/env-vars/index.vue
- 云原生应用：环境变量唯一性判断不正确
- footer 展示优化
=> fix: 云原生应用：环境变量唯一性判断不正确，footer 展示优化

apiserver/paasng/paasng/platform/sourcectl/models.py
- chore: remove dead code in sourcectl.models
=> chore: remove dead code in sourcectl.models

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/index.vue
=> update: 创建新令牌功能根据特性展示

webfe/package_vue/index.dev.html, webfe/package_vue/index.html, webfe/package_vue/src/common/platform-config.js, webfe/package_vue/src/components/paas-footer.vue, webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/store/index.js
=> fix: 全局配置字段对接修改

webfe/package_vue/src/App.vue
=> fix: 平台公告无法获取修复

webfe/package_vue/src/json/instance-chart-option.js, webfe/package_vue/src/json/process-chart-option.js
=> update: 进程详情中，CPU requests值展示优化

webfe/package_vue/src/views/dev-center/home/idle-app-dashboard.vue
- 闲置应用下架操作对齐问题修复
- 闲置应用下架、退出应用的二次确认框都用气泡的样式
=> fix: 闲置应用下架操作对齐问题修复、闲置应用下架、退出应用的二次确认框都用气泡的样式

apiserver/paasng/paasng/accessories/cloudapi/views.py, apiserver/paasng/tests/paasng/accessories/cloudapi/test_views.py
=> refactor: simplifying code implementation of CloudAPIViewSet

apiserver/paasng/paas_wl/bk_app/applications/models/build.py
=> refactor: ignore ResourceNotFound when no image found

README.md, cloudnative-buildpacks/README.md
=> docs: fix some description in readme

webfe/package_vue/src/components/app-migration-dialog/index.vue
=> fix: 普通应用迁移云原生错误弹窗处理

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/probe/index.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/probe/probe-form.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-hook.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
=> fix: 探针7-5体验问题修复

apiserver/paasng/conf.yaml.tpl, apiserver/paasng/paas_wl/bk_app/cnative/specs/resource.py, apiserver/paasng/paas_wl/infras/resources/base/kres.py, apiserver/paasng/paas_wl/workloads/networking/ingress/managers/domain.py, apiserver/paasng/paas_wl/workloads/networking/ingress/managers/subpath.py, apiserver/paasng/paasng/platform/applications/views.py, apiserver/paasng/paasng/platform/engine/deploy/archive/operator.py, apiserver/paasng/paasng/settings/workloads.py, apiserver/paasng/tests/paas_wl/workloads/networking/ingress/managers/test_domain.py, apiserver/paasng/tests/paas_wl/workloads/networking/ingress/managers/test_subpath.py, operator/api/v1alpha1/projectconfig_types.go, operator/api/v1alpha1/projectconfig_types_test.go, operator/config/crd/bases/paas.bk.tencent.com_projectconfigs.yaml, operator/main.go, operator/pkg/config/config.go, operator/pkg/controllers/dgroupmapping/ingress/builder.go, operator/pkg/controllers/dgroupmapping/ingress/builder_test.go
=> feat: support set custom domain ingress class separately

webfe/package_vue/src/components/global-search/search-input.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/app-services.vue
=> fix: 全局搜索focus兼容通知中心

apiserver/paasng/paasng/accessories/log/views/legacy.py, apiserver/paasng/paasng/accessories/publish/entrance/views.py, apiserver/paasng/paasng/accessories/servicehub/views.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/views.py, apiserver/paasng/paasng/infras/accounts/permissions/application.py, apiserver/paasng/paasng/misc/monitoring/monitor/views.py, apiserver/paasng/paasng/plat_admin/system/views.py, apiserver/paasng/paasng/platform/applications/mixins.py, apiserver/paasng/paasng/platform/applications/views.py, apiserver/paasng/paasng/platform/modules/views.py, apiserver/paasng/paasng/utils/views.py, apiserver/paasng/tests/paasng/test_utils/test_view.py
- refactor: improve the permission_classes decorator by add more comments and better naming.
=> refactor: improve the permission_classes decorator by add more comments and better naming.

apiserver/paasng/paas_wl/bk_app/cnative/specs/crd/bk_app.py, apiserver/paasng/paas_wl/bk_app/cnative/specs/procs/replicas.py, apiserver/paasng/paasng/platform/bkapp_model/importer/env_overlays.py, apiserver/paasng/paasng/platform/bkapp_model/importer/importer.py, apiserver/paasng/paasng/platform/bkapp_model/importer/processes.py, apiserver/paasng/paasng/platform/bkapp_model/importer/serializers.py, apiserver/paasng/paasng/platform/declarative/deployment/controller.py, apiserver/paasng/paasng/platform/declarative/deployment/resources.py, apiserver/paasng/paasng/platform/declarative/deployment/validations/v2.py, apiserver/paasng/paasng/platform/engine/utils/patcher.py, apiserver/paasng/tests/paas_wl/infras/resources/utils/test_app.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_importer.py, apiserver/paasng/tests/paasng/platform/declarative/deployment/v2/test_controller.py, apiserver/paasng/tests/paasng/platform/engine/utils/test_source.py
- fix: replicas alway reset to 1 when processes defined in app_desc.yaml
=> fix: replicas alway reset to 1 when processes defined in app_desc.yaml

webfe/package_vue/src/views/index.vue
=> fix: 云原生应用的部署操作跳转地址不对修复 & 冗余代码删除

apiserver/paasng/support-files/apigw/api_doc/en/get_deploy_phases_framework.md, apiserver/paasng/support-files/apigw/api_doc/en/get_deploy_phases_instance.md, apiserver/paasng/support-files/apigw/api_doc/en/list_processes.md, apiserver/paasng/support-files/apigw/api_doc/en/search_structured_log.md, apiserver/paasng/support-files/apigw/api_doc/en/search_structured_log_with_post.md, apiserver/paasng/support-files/apigw/api_doc/en/upload_source_package_via_link.md, apiserver/paasng/support-files/apigw/api_doc/zh/get_deploy_phases_framework.md, apiserver/paasng/support-files/apigw/api_doc/zh/get_deploy_phases_instance.md, apiserver/paasng/support-files/apigw/api_doc/zh/list_processes.md, apiserver/paasng/support-files/apigw/api_doc/zh/search_structured_log.md, apiserver/paasng/support-files/apigw/api_doc/zh/search_structured_log_with_post.md, apiserver/paasng/support-files/apigw/api_doc/zh/upload_source_package_via_link.md
modify doc of get_deploy_phases_framework, get_deploy_phases_instance, list_processes.
=> Docs improvements：get deploy phases , list processes

apiserver/paasng/paasng/platform/bkapp_model/manifest.py
=> fix: first got unexpected keyword

operator/scripts/update_helm_chart.py
=> chore: add customDomainIngressClassName in update_helm_chart.py

apiserver/paasng/paasng/plat_admin/initialization/management/commands/init_bkrepo.py
=> feat: add apigw-bkrepo init

webfe/package_vue/package.json, webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/visit-config.vue
=> fix: 访问地址表格固定列不对齐优化

webfe/package_vue/src/store/modules/create-app.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/index.vue, webfe/package_vue/src/views/dev-center/app/market/market-manager.vue, webfe/package_vue/src/views/dev-center/app/services/instance.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.vue, webfe/package_vue/src/views/dev-center/create-app/external.vue, webfe/package_vue/src/views/dev-center/create-app/main.vue, webfe/package_vue/src/views/dev-center/create-app/smart.vue
- 增强服务详情点击“模块配置”页面，样式错误
- 市场信息编辑取消后回显问题修复
- 创建应用时，如果先点击了蓝鲸插件后，再切换到创建镜像仓库会提示蓝鲸插件的报错修复
=> fix：体验提单修复1.5

apiserver/paasng/paasng/infras/bkmonitorv3/params.py, apiserver/paasng/paasng/misc/monitoring/monitor/views.py, apiserver/paasng/tests/paasng/misc/monitoring/test_alert.py
因监控的有损升级，bk_biz_ids 参数不再支持 str 类型
=> fix: fix alerts query

apiserver/paasng/paasng/settings/__init__.py
=> fix: 带端口的镜像地址解析问题 #1576

webfe/package_vue/src/components/global-search/search-input.vue, webfe/package_vue/src/components/paas-header.vue
=> fix: nav 顶部样式规范调整

webfe/package_vue/src/components/paas-header.vue
- nav 顶部样式规范调整 （1.5分支代码落后于主分支代码，存在lint与样式上的差异）
=> fix：nav 顶部样式规范调整

apiserver/paasng/tests/paasng/platform/declarative/deployment/v2/test_controller.py
=> test: fix unit test

apiserver/paasng/paasng/misc/monitoring/monitor/urls.py, apiserver/paasng/paasng/misc/monitoring/monitor/views.py
=> feat: add get metric dashboard url api

webfe/package_vue/src/components/user-selector/index.vue, webfe/package_vue/src/components/user-selector/request.js, webfe/package_vue/src/views/dev-center/app/market/render-member-list.vue, webfe/package_vue/src/views/dev-center/app/market/visible-range.vue
-  组织架构选择器不使用 fe_list_department_profiles API
=> fix: 组织架构选择器不使用 fe_list_department_profiles API

apiserver/paasng/paasng/platform/declarative/application/controller.py, apiserver/paasng/tests/paasng/platform/declarative/application/v2/test_controller.py, apiserver/paasng/tests/paasng/platform/declarative/application/v3/test_controller.py, apiserver/paasng/tests/paasng/platform/declarative/conftest.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v2/test_app.py
- fix: creating new module for s-mart app via YAML file might use the wrong cluster
=> fix: creating new module for s-mart app via YAML file might use the wrong cluster

webfe/package_vue/src/views/plugin-center/plugin/base-config/base-info.vue
=> fix:  Codecc 插件下架插件无法操作

apiserver/README.md
docs: update README.md to add detailed intro of E2E tests
=> docs: update README.md to add detailed intro of E2E tests 

webfe/package_vue/src/views/dev-center/home/home-content/alarm-records.vue, webfe/package_vue/src/views/dev-center/home/home-content/index.vue
- 告警记录样式问题修复，去掉退出应用
- 告警记录切换高亮修复
=> fix: 样式修复 & 告警去掉退出应用

webfe/package_vue/src/common/utils.js, webfe/package_vue/src/store/modules/application.js, webfe/package_vue/src/views/dev-center/app/basic-config/module-manage.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/code-source.vue, webfe/package_vue/src/views/dev-center/app/engine/deployment/comps/deploy-action/index.vue, webfe/package_vue/src/views/dev-center/create-app/success-git.scss, webfe/package_vue/src/views/dev-center/create-app/success-git.vue
=> feat: 初始化模板下载地址

apiserver/paasng/paasng/platform/bkapp_model/manager.py
=> fix: incorrectly updated the number of replicas for Procfile app

webfe/package_vue/src/views/dev-center/app/operation-record/comps/code-diff.vue, webfe/package_vue/src/views/dev-center/app/operation-record/comps/diff.vue, webfe/package_vue/src/views/dev-center/app/operation-record/index.vue
- 操作审计数据对比，若 data_before/data_after 任一为空，无需请求
- 操作审计diff更换主题方案
=> fix: 操作审计提单修复

webfe/package_vue/src/App.vue, webfe/package_vue/src/views/plugin-center/create-plugin/success.vue, webfe/package_vue/static/login_success.html
=> fix: 优化插件指引链接 & 401弹窗问题修复

webfe/package_vue/src/views/dev-center/sandbox/index.vue
=> fix: 沙箱根据环境决定当前协议

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue
- 云原生替换 processes/list 接口中对外层 cpu_limit/memory_limit 字段
- 格式化
=> fix: 云原生替换 processes/list 接口中对外层 cpu_limit/memory_limit 字段

apiserver/paasng/paas_wl/bk_app/processes/views.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/processes.py, apiserver/paasng/paasng/platform/bkapp_model/fieldmgr/fields.py, apiserver/paasng/paasng/platform/bkapp_model/fieldmgr/managers.py, apiserver/paasng/paasng/platform/bkapp_model/serializers/serializers.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_importer.py
- feat: add field_manager field for svc_disc/domain_res API
- refactor: enhance field management for target replicas and autoscaling in process synchronization
=> feat: add field_manager field for svc_disc/domain_res API

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue, webfe/package_vue/src/views/dev-center/app/engine/entry-config/comps/access-process.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.scss, webfe/package_vue/src/views/dev-center/create-app/cloud.vue
- 进程服务管理：应用没有名为 default 模块时报错修复
- 创建应用时，镜像凭证名称添加校验规则
- 创建应用时不应请求关于携带code的接口 
- lint
=> fix：体验提单修复 

apiserver/paasng/locale/en/LC_MESSAGES/django.po, apiserver/paasng/paasng/platform/smart_app/views.py
=> fix: allowed mismatched smart app to upload

webfe/package_vue/src/views/dev-center/create-app/cloud.vue
- 创建应用，镜像凭证名称非必填，如果填写了的话需要校验镜像名称
=> fix: 创建应用，镜像凭证名称非必填，如果填写了的话需要校验镜像名称

webfe/package_vue/src/views/dev-center/app/operation-record/comps/code-diff.vue, webfe/package_vue/src/views/dev-center/app/operation-record/comps/diff.vue, webfe/package_vue/src/views/dev-center/app/operation-record/index.vue, webfe/package_vue/src/views/dev-center/home/home-content/alarm-records.vue, webfe/package_vue/src/views/dev-center/home/home-content/index.vue, webfe/package_vue/src/views/plugin-center/plugin/base-config/operation-records.vue
- 操作详情添加全屏操作
- 首页在刷新过程中会隐性显示没有开启的功能
=> fix: 测试提单修复 

apiserver/paasng/paas_wl/bk_app/applications/models/build.py, apiserver/paasng/paasng/platform/engine/serializers.py
=> refactor: allow unknown version when image is exist

webfe/package_vue/src/views/dev-center/index.vue, webfe/package_vue/src/views/plugin-center/comps/filter-select.vue, webfe/package_vue/src/views/plugin-center/index.vue
- 应用列表：默认按最近操作时间排序
- 插件列表添加过滤下拉，默认按照最新操作时间排序
=> fix: 插件列表添加过滤下拉、应用列表：默认按最近操作时间排序

apiserver/paasng/paasng/platform/bkapp_model/serializers/v1alpha2.py
=> refactor: set allow_blank=True for value field in BaseEnvVarFields

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/sandbox-dialog.vue, webfe/package_vue/src/views/dev-center/app/operation-record/index.vue, webfe/package_vue/src/views/dev-center/create-app/external.vue
- 文案优化
- 外链应用：创建应用时页面上不展示“应用版本”
=> fix:  体验修复

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/app-description-file.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-env.vue, webfe/package_vue/src/views/plugin-center/create-plugin/index.vue
- 插件中心-创建应用-语言去重
- 环境变量空数据样式优化
=> fix：体验单据修复

webfe/package_vue/src/views/plugin-center/create-plugin/index.vue
=> fix: 同类型模板无法选择bug修复

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-detail.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-status-detail.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/scale-dialog.vue
=> fix: 进程操作优化 & lint

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/comps/deploy-build/code-source.vue
=> fix: 代码检查详情交互优化

webfe/package_vue/src/views/dev-center/sandbox/comps/run-sandbox-dialog.vue, webfe/package_vue/src/views/dev-center/sandbox/index.vue
process 格式修改
修改前 map[string]struct{Command string}
修改后 []struct{Name string
ProcCommand string}
=> fix: 修改沙箱运行进程的数据结构

webfe/package_vue/package.json, webfe/package_vue/src/store/modules/deploy.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-module-list.vue
=> feat: 部署管理模块列表拖拽排序

apiserver/paasng/paas_wl/infras/resources/base/base.py, apiserver/paasng/paasng/settings/__init__.py, apiserver/paasng/tests/paas_wl/conftest.py
=> feat: support reload from db when cluster config update

apiserver/paasng/paas_wl/infras/resources/base/base.py
=> docs: func docs

webfe/package_vue/src/views/dev-center/app/engine/env-vars/index.vue
- tooltips content为 * * .. 导致页面渲染错误, 出现白屏情况
=> bug: tooltips content为 * * .. 导致页面渲染错误, 出现白屏情况

apiserver/paasng/paasng/accessories/servicehub/remote/manager.py, apiserver/paasng/paasng/accessories/servicehub/serializers.py
- feat: add region field to ServiceAttachmentDetailedSLZ serializer
=> feat: add region field to ServiceAttachmentDetailedSLZ serializer

apiserver/paasng/conf.yaml.tpl, apiserver/paasng/paas_wl/workloads/networking/entrance/views.py, apiserver/paasng/paas_wl/workloads/networking/ingress/entities.py, apiserver/paasng/paas_wl/workloads/networking/ingress/exceptions.py, apiserver/paasng/paasng/accessories/servicehub/serializers.py, apiserver/paasng/paasng/accessories/servicehub/urls.py, apiserver/paasng/paasng/accessories/servicehub/views.py, apiserver/paasng/paasng/core/region/models.py, apiserver/paasng/paasng/core/region/states.py, webfe/package_vue/src/store/modules/create-app.js, webfe/package_vue/src/views/dev-center/app/create-cloud-module/index.vue, webfe/package_vue/src/views/dev-center/app/create-module/index.vue, webfe/package_vue/src/views/dev-center/create-app/default.vue
- refactor: clean up comments and improve parameter defaults in configuration files
=> refactor: clean up comments and improve parameter defaults in configuration files

webfe/package_vue/src/common/event-tracking.js, webfe/package_vue/src/components/cloud-app-top-bar.vue, webfe/package_vue/src/main.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/index.vue, webfe/package_vue/src/views/dev-center/app/engine/entry-config/index.vue, webfe/package_vue/src/views/dev-center/app/engine/log/index.vue
=> fix: 埋点前置判断

apiserver/paasng/locale/en/LC_MESSAGES/django.po, apiserver/paasng/paasng/platform/applications/serializers/fields.py, apiserver/paasng/paasng/platform/smart_app/serializers.py, apiserver/paasng/paasng/platform/smart_app/services/detector.py, apiserver/paasng/paasng/platform/smart_app/views.py
=> fix: smart app code can use with char _ and length between 3-20

apiserver/paasng/locale/en/LC_MESSAGES/django.po, apiserver/paasng/paasng/platform/smart_app/views.py
=> docs: change "S-Mart" to "S-mart"

webfe/package_vue/src/components/paas-cloud-app-nav.vue
=> fix: 云原生导航宽度问题修复

apiserver/paasng/paas_wl/infras/resources/base/kube_client.py
=> feat: ignore some crd missing kind field

apiserver/paasng/paas_wl/bk_app/applications/models/build.py, apiserver/paasng/paasng/platform/engine/deploy/bg_build/bg_build.py
应该允许在 pre release hook 阶段，成功中断部署流程
=> fix: raise interrupt error when build process is finished

apiserver/paasng/paasng/platform/sourcectl/models.py, apiserver/paasng/paasng/platform/sourcectl/views.py
=> docs: add comments explaining why SvnAccount no need tenant_id field

apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/domain_resolution.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/hooks.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/proc_env_overlays.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/processes.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/svc_discovery.py, apiserver/paasng/paasng/platform/bkapp_model/fieldmgr/managers.py, apiserver/paasng/tests/paasng/platform/bkapp_model/fieldmgr/test_managers.py, apiserver/paasng/tests/paasng/platform/declarative/deployment/v2/test_controller.py, apiserver/paasng/tests/paasng/platform/declarative/deployment/v3/test_controller.py
=> fix: bkapp_model entity sync error when some field missing manager

webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/sandbox-sideslider.vue
- 沙箱开发。当只有一个模块并创建沙箱时，首次进入table渲染错误
=> bug: 沙箱开发。当只有一个模块并创建沙箱时，首次进入table渲染错误

apiserver/paasng/paasng/settings/__init__.py, apiserver/paasng/paasng/settings/utils.py, apiserver/poetry.lock, apiserver/pyproject.toml
=> feat: django CACHE setting support redis sentinel url config

webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/app-perm.vue, webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/comps/apply-record.vue, webfe/package_vue/src/views/dev-center/app/basic-config/cloud-api/index.vue
- 云 API 权限中 ”组件“ 根据 FeatureFlag 判断是否展示
=> fix: 云 API 权限中 ”组件“ 根据 FeatureFlag 判断是否展示

apiserver/paasng/paasng/platform/bkapp_model/services.py, apiserver/paasng/paasng/platform/engine/deploy/building.py, apiserver/paasng/paasng/platform/engine/deploy/image_release.py
=> fix: not set process service flag when deploy with build image directly

apiserver/paasng/paas_wl/apis/admin/views/processes.py, apiserver/paasng/paas_wl/bk_app/processes/models.py, apiserver/paasng/tests/api/apigw/test_system_apis.py, apiserver/paasng/tests/api/test_build_config.py, apiserver/paasng/tests/api/test_market.py, apiserver/paasng/tests/api/test_smart_app.py, apiserver/paasng/tests/api/test_sourcectl.py, apiserver/paasng/tests/api/test_templates.py, apiserver/paasng/tests/conftest.py, apiserver/paasng/tests/paasng/accessories/publish/sync_market/test_sync_console.py
- refactor: more on removing inproper use of region field, part 1
=> refactor: more on removing inproper use of region field, part 1

webfe/package_vue/src/views/platform/app-cluster/config.vue
=> fix：统一分配，预发布环境展示错误

webfe/package_vue/src/views/platform/app-cluster/comps/cluster-transfer.vue
=> fix: 集群分配策略顺序异常

webfe/package_vue/src/views/dev-center/app/engine/env-vars/index.vue
- tooltips content为 * * .. 导致页面渲染错误, 出现白屏情况
=> fix: tooltips content为 * * .. 导致页面渲染错误, 出现白屏情况

webfe/package_vue/src/views/dev-center/app/engine/app-migration-info/comps/migration-process-management.vue, webfe/package_vue/src/views/dev-center/app/engine/app-migration-info/comps/scaling-dialog.vue
=> fix: 迁移信息空数据结构变化处理

webfe/package_vue/src/views/platform/app-cluster/cluster-viewpoint.vue, webfe/package_vue/src/views/platform/app-cluster/comps/cluster-details.vue
=> fix: 集群进度去掉背景色

apiserver/paasng/paasng/platform/engine/processes/views.py
=> fix: cnb smart-app not use launcher bash

apiserver/paasng/paas_wl/infras/cluster/entities.py, apiserver/paasng/paasng/accessories/publish/entrance/preallocated.py, apiserver/paasng/tests/paasng/accessories/publish/entrance/test_preallocated.py, pyproject.toml
- fix: handle non-existent application codes when getting pre-allocated addrs
=> fix: handle non-existent application codes when getting pre-allocated addrs

apiserver/paasng/paasng/misc/plat_config/views.py, apiserver/paasng/paasng/platform/engine/configurations/config_var.py
=> feat: add built-in env BKPAAS_MULTI_TENANT_MODE & add MULTI_TENANT_MODE constant for webfe

apiserver/Dockerfile, apiserver/dev_utils/unittest/Dockerfile.devops.unittest, apiserver/paasng/paasng/infras/perm_insure/apps.py, apiserver/paasng/paasng/infras/perm_insure/views_perm.py, apiserver/paasng/tests/paasng/bk_plugins/pluginscenter/test_sys_apis.py, apiserver/paasng/tests/paasng/infras/test_perm_insure.py
- feat: use Django check frameword for view permission configuration
=> feat: use Django check framework for view permission configuration

apiserver/paasng/paasng/platform/bkapp_model/serializers/serializers.py, apiserver/paasng/paasng/platform/bkapp_model/serializers/v1alpha2.py
=> refactor: add process service name invalid error message

apiserver/paasng/paasng/bk_plugins/bk_plugins/api_serializers.py, apiserver/paasng/paasng/bk_plugins/bk_plugins/pluginscenter_views.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/serializers.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/thirdparty/api_serializers.py, apiserver/paasng/paasng/infras/perm_insure/views_perm.py, apiserver/paasng/paasng/plat_admin/api_doc/generators.py, apiserver/paasng/paasng/platform/applications/views/creation.py, apiserver/paasng/paasng/platform/engine/serializers.py
- fix: api docs wont render becaues the error raised by SysAPIClientPermission
=> fix: api docs wont render becaues the error raised by SysAPIClientPermission

operator/pkg/controllers/dgroupmapping/ingress/plugins.go, operator/pkg/platform/applications/info.go
=> refactor: rename TenantID to AppTenantID in operator

webfe/package_vue/src/language/lang/platform-management/en.js, webfe/package_vue/src/language/lang/platform-management/zh.js, webfe/package_vue/src/views/platform/app-cluster/cluster-create-edit/index.vue
=> fix: 集群管理：步骤优化

operator/pkg/controllers/bkapp/deploy_action.go, operator/pkg/controllers/bkapp/deploy_action_test.go, operator/pkg/controllers/bkapp/hooks/hooks.go, operator/pkg/controllers/bkapp/hooks/hooks_test.go
=> fix: incorrectly read hook starttime from last hook instance sometimes

apiserver/paasng/paas_wl/bk_app/applications/models/build.py
忽略原因：由于支持集群绑定不同的镜像仓库，因此可能出现切换绑定后，新的镜像凭证无法获取历史构建镜像信息的情况，这里需要进行忽略
=> fix: ignore retrieve image artifact details failure

operator/config/manager/controller_manager_config.yaml, operator/scripts/update_helm_chart.py
=> fix: missing tenantGuard in config.yaml

apiserver/paasng/paasng/accessories/publish/market/serializers.py
=> feat: visiableLabels 的 id 允许填写字符串

apiserver/paasng/paasng/platform/engine/views/configvar.py, apiserver/paasng/tests/api/test_configvar_by_key.py
Cherry pick pr2121 to release 1.6
=> fix: 修复创建全局变量时 is_global 不为 true

webfe/package_vue/src/views/dev-center/app/basic-config/members-sideslider.vue
=> fix: 侧栏小屏滚动

apiserver/paasng/paasng/platform/bkapp_model/models.py
=> fix: proc_command string not strip

apiserver/paasng/paasng/platform/engine/deploy/release/operator.py
=> fix: not abort when deploy bk/grpc BkApp

apiserver/paasng/paasng/platform/engine/deploy/release/operator.py
=> fix: missing DeployStep.procedures decorator on BkAppReleaseMgr.start

apiserver/paasng/paasng/platform/smart_app/management/commands/smart_tool.py
=> refactor: update smart tool to make it reentrant

apiserver/paasng/paas_wl/bk_app/cnative/specs/resource.py
=> fix: use ExposedTypeName.BK_GRPC as domain protocol incorrectly

apiserver/paasng/paasng/platform/bkapp_model/entities/proc_service.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/tests/api/bkapp_model/test_bkapp_model.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_render_port.py
=> refactor: render port and target port when query proc spec data

apiserver/paasng/paasng/infras/perm_insure/conf.py, apiserver/paasng/paasng/misc/tools/serializers.py, apiserver/paasng/paasng/misc/tools/urls.py, apiserver/paasng/paasng/misc/tools/views.py, apiserver/paasng/tests/api/test_smart_app.py
=> feat: add upload code package api for build smart

apiserver/paasng/paasng/platform/applications/views/application.py, operator/pkg/config/config.go, operator/pkg/controllers/dgroupmapping/ingress/builder.go, operator/pkg/controllers/dgroupmapping/ingress/builder_test.go, operator/pkg/testing/config.go
=> fix: set customDomainIngressClassName not work

apiserver/paasng/paasng/platform/sourcectl/package/client.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/test_client.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/utils.py
=> feat: add link checking for BinaryTar

apiserver/paasng/paasng/accessories/smart_advisor/tagging.py, apiserver/paasng/paasng/platform/engine/configurations/source_file.py, apiserver/paasng/paasng/platform/engine/utils/source.py, apiserver/paasng/paasng/platform/smart_app/services/detector.py, apiserver/paasng/paasng/platform/sourcectl/client.py, apiserver/paasng/paasng/platform/sourcectl/controllers/bare_git.py, apiserver/paasng/paasng/platform/sourcectl/controllers/gitee.py, apiserver/paasng/paasng/platform/sourcectl/controllers/github.py, apiserver/paasng/paasng/platform/sourcectl/controllers/gitlab.py, apiserver/paasng/paasng/platform/sourcectl/exceptions.py, apiserver/paasng/paasng/platform/sourcectl/gitlab/client.py, apiserver/paasng/paasng/platform/sourcectl/package/client.py, apiserver/paasng/paasng/platform/sourcectl/repo_controller.py, apiserver/paasng/paasng/platform/sourcectl/svn/client.py, apiserver/paasng/paasng/platform/sourcectl/svn/exceptions.py, apiserver/paasng/tests/paasng/accessories/smart_advisor/test_tagging.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/test_client.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/utils.py, apiserver/paasng/tests/paasng/platform/sourcectl/test_bare_git.py
- refactor: refactor the exception types in package/client
=> refactor: refactor the exception types in package/client

apiserver/paasng/paasng/accessories/smart_advisor/tagging.py, apiserver/paasng/paasng/platform/engine/configurations/source_file.py, apiserver/paasng/paasng/platform/engine/utils/source.py, apiserver/paasng/paasng/platform/smart_app/services/detector.py, apiserver/paasng/paasng/platform/sourcectl/client.py, apiserver/paasng/paasng/platform/sourcectl/controllers/bare_git.py, apiserver/paasng/paasng/platform/sourcectl/controllers/gitee.py, apiserver/paasng/paasng/platform/sourcectl/controllers/github.py, apiserver/paasng/paasng/platform/sourcectl/controllers/gitlab.py, apiserver/paasng/paasng/platform/sourcectl/exceptions.py, apiserver/paasng/paasng/platform/sourcectl/gitlab/client.py, apiserver/paasng/paasng/platform/sourcectl/package/client.py, apiserver/paasng/paasng/platform/sourcectl/repo_controller.py, apiserver/paasng/paasng/platform/sourcectl/svn/client.py, apiserver/paasng/paasng/platform/sourcectl/svn/exceptions.py, apiserver/paasng/tests/paasng/accessories/smart_advisor/test_tagging.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/test_client.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/utils.py, apiserver/paasng/tests/paasng/platform/sourcectl/test_bare_git.py
refactor: refactor the exception types in package/client (#2292)
=> refactor: refactor the exception types in package/client (#2292)

apiserver/paasng/paasng/platform/sourcectl/controllers/bare_git.py
=> fix: add missing Path import

apiserver/paasng/paasng/accessories/servicehub/manager.py, apiserver/paasng/paasng/accessories/servicehub/sharing.py, apiserver/paasng/paasng/accessories/servicehub/urls.py, apiserver/paasng/paasng/accessories/servicehub/views.py, apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/engine/configurations/config_var.py, apiserver/paasng/paasng/platform/engine/configurations/env_var/entities.py, apiserver/paasng/paasng/platform/engine/configurations/env_var/listers.py, apiserver/paasng/paasng/platform/engine/models/config_var.py, apiserver/paasng/paasng/platform/engine/serializers.py, apiserver/paasng/paasng/platform/engine/urls.py, apiserver/paasng/paasng/platform/engine/views/__init__.py, apiserver/paasng/paasng/platform/engine/views/configvar.py, apiserver/paasng/tests/api/test_servicehub.py, apiserver/paasng/tests/paasng/platform/engine/configurations/env_var/test_listers.py, apiserver/paasng/tests/paasng/platform/engine/configurations/test_config_var.py, apiserver/paasng/tests/paasng/platform/engine/conftest.py, apiserver/paasng/tests/paasng/platform/engine/test_config_var.py, apiserver/paasng/tests/utils/mocks/services.py
feat: add get conflicted config var keys API
=> feat: add get conflicted config var keys API

apiserver/paasng/paasng/accessories/servicehub/remote/manager.py, apiserver/paasng/paasng/accessories/smart_advisor/utils.py, apiserver/paasng/paasng/misc/tools/serializers.py, apiserver/paasng/paasng/misc/tools/views.py, apiserver/paasng/paasng/plat_admin/numbers/app.py, apiserver/paasng/paasng/platform/engine/views/configvar.py, apiserver/paasng/paasng/utils/safe_jinja2.py, apiserver/paasng/paasng/utils/text.py, apiserver/paasng/tests/paasng/test_utils/test_text.py
- refactor: replace str.format with safe_jinja2/safe_str_format
=> refactor: replace str.format with safe_jinja2/safe_str_format

apiserver/paasng/paasng/platform/sourcectl/package/client.py, apiserver/paasng/paasng/platform/sourcectl/utils.py, apiserver/paasng/paasng/utils/basic.py
- fix: replace unsafe option for Popen
=> fix: replace unsafe option for Popen

apiserver/paasng/paasng/platform/smart_app/services/detector.py, apiserver/paasng/paasng/utils/file.py, apiserver/paasng/paasng/utils/serializers.py, apiserver/paasng/paasng/utils/text.py, apiserver/paasng/tests/paasng/test_utils/test_file.py, apiserver/paasng/tests/paasng/test_utils/test_serializers.py
- refactor: add path checking when detetor determine relative path
=> refactor: add path checking when detetor determine relative path

apiserver/paasng/paas_wl/infras/cluster/loaders.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/management/commands/create_or_update_plugin_type.py, apiserver/paasng/paasng/platform/engine/configurations/source_file.py, apiserver/paasng/paasng/platform/smart_app/services/detector.py, apiserver/paasng/tests/paas_wl/bk_app/monitoring/app_monitor/test_managers.py, apiserver/paasng/tests/paas_wl/infras/resources/base/test_kres.py, apiserver/paasng/tests/paasng/platform/engine/utils/test_source.py, apiserver/paasng/tests/paasng/platform/smart_app/test_patcher.py
- refactor: standardize the usage of yaml module
=> refactor: standardize the usage of yaml module

webfe/Dockerfile, webfe/rootfs/base/root/etc/cont-init.d/30-resolver, webfe/rootfs/base/root/etc/cont-init.d/40-resolver, webfe/rootfs/base/root/etc/services.d/resolver/run, webfe/rootfs/base/root/usr/bin/host-ip, webfe/rootfs/base/root/usr/bin/set-contenv, webfe/rootfs/nginx/root/etc/nginx/conf.d/default.conf, webfe/rootfs/nginx/root/etc/nginx/nginx.conf, webfe/rootfs/nginx/root/etc/services.d/nginx/finish, webfe/rootfs/nginx/root/etc/services.d/nginx/run, webfe/rootfs/nginx/root/usr/html/index.html
升级前端  webfe 的系统镜像到 alpine 3.22.1
=> chore: update webfe base image

apiserver/paasng/paasng/platform/engine/deploy/release/legacy.py, apiserver/paasng/paasng/platform/engine/views/release.py
- fix: call /releases/ API unexpectly modified the stats of latest deployment
=> fix: call /releases/ API unexpectly modified the stats of latest deployment

apiserver/paasng/paasng/platform/engine/configurations/config_var.py, apiserver/paasng/tests/paasng/platform/engine/configurations/test_config_var.py
- fix: env var ENGINE_REGION value is blank
=> fix: env var ENGINE_REGION value is blank

apiserver/paasng/paasng/platform/engine/models/config_var.py, apiserver/paasng/paasng/platform/engine/models/preset_envvars.py, apiserver/paasng/paasng/utils/models.py
- fix: EncryptField unable to process values that starts with special header
=> fix: EncryptField unable to process values that starts with special header

cnb-builder-shim/cmd/lifecycle-driver/main.go, cnb-builder-shim/pkg/lifecycle/phase/analyzer.go, cnb-builder-shim/pkg/lifecycle/phase/builder.go, cnb-builder-shim/pkg/lifecycle/phase/detector.go, cnb-builder-shim/pkg/lifecycle/phase/exporter.go, cnb-builder-shim/pkg/lifecycle/phase/restorer.go
=> fix: restorer command has no -daemon args in Platform API version 0.11

apiserver/paasng/paasng/infras/notifier/client.py, apiserver/paasng/paasng/platform/sourcectl/package/client.py, apiserver/paasng/paasng/platform/sourcectl/utils.py
相关问题:
- https://github.com/TencentBlueKing/blueking-paas/security/code-scanning/53
- https://github.com/TencentBlueKing/blueking-paas/security/code-scanning/50
=> fix: some security issues

smart-app-builder/README.md, smart-app-builder/pkg/builder/executor/container.go, smart-app-builder/pkg/builder/executor/utils.go, smart-app-builder/pkg/config/config.go
=> feat: support image cache when build

apiserver/paasng/paasng/platform/engine/configurations/source_file.py
- refactor: remove the error_tips prop on the MetaDataFileReader type and improve the error message
=> refactor: remove the error_tips prop on the MetaDataFileReader type and improve the error message

apiserver/paasng/paasng/platform/engine/deploy/building.py
- doc: add comment for the dockerignore file logic
=> doc: add comment for the dockerignore file logic

apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/404.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/base.html, apiserver/paasng/paasng/plat_admin/admin42/urls.py, apiserver/paasng/paasng/plat_admin/admin42/views/__init__.py
=> feat: 访问 admin42 中不存在的路径时返回功能迁移通知页面

apiserver/paasng/paas_wl/workloads/networking/ingress/domains/manager.py
=> docs: support custom domain with https scheme

apiserver/paasng/paas_wl/bk_app/applications/api.py, apiserver/paasng/paasng/platform/engine/processes/views.py
=> fix: incorrect entry command to access smartapp webconsole

apiserver/paasng/paasng/platform/sourcectl/package/client.py, apiserver/paasng/tests/paasng/platform/sourcectl/packages/test_controller.py
=> refactor: get_client for package only return GenericRemoteClient
