apiserver/paasng/paasng/engine/controller/models.py, apiserver/paasng/paasng/publish/entrance/domains.py, apiserver/paasng/paasng/publish/entrance/exposer.py, apiserver/paasng/paasng/publish/entrance/subpaths.py, apiserver/paasng/tests/engine/controller/test_models.py, apiserver/paasng/tests/publish/entrance/test_domains.py, apiserver/paasng/tests/publish/entrance/test_subpaths.py, apiserver/paasng/tests/publish/test_entrance.py, workloads/paas_wl/paas_wl/cnative/specs/addresses.py
- 增加 `*Allocator` 类型，汇聚子路径和子域名生成逻辑，消除重复
- 增加 `make_user_preferred_one` 相关的单元测试代码
=> 重构生成默认子路径/子域名相关代码，消除重复的算法逻辑

apiserver/paasng/paasng/plat_admin/system/serializers.py, apiserver/paasng/paasng/plat_admin/system/views.py, operator/hack/boilerplate.go.txt, operator/pkg/controllers/resources/configuration.go, operator/pkg/platform/external/addons.go, operator/pkg/platform/external/addons_test.go
根据约定 query_credentials 应该返回的是 Dict[str, str], 但是目前来看这个约定被 GCS-MySQL 这个增强服务打破了。
这个 MR 从两个方面修复这个问题:
- apiserver 添加 slz 做类型转换，保证接口符合约定
- operator 加上对 int 类型的支持, 修复线上问题
=> bugfix: 修复增强服务环境变量不支持 int 类型的问题

apiserver/paasng/paasng/engine/deploy/building.py, apiserver/paasng/paasng/engine/deploy/image.py
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/code.py", line 90, in runcode
exec(code, self.locals)
File "<console>", line 1, in <module>
File "/app/paasng/extensions/declarative/handlers.py", line 147, in handle_deployment
controller.perform_action(self.get_deploy_desc(deployment.app_environment.module.name))
File "/app/paasng/extensions/declarative/handlers.py", line 121, in get_deploy_desc
raise DescriptionValidationError({"module": _('内容不能为空')})
```
例如, 以上异常会打印  `应用描述文件解析异常: module: 内容不能为空`
=> enhance: 将应用描述文件解析失败的信息暴露给用户

workloads/paas_wl/paas_wl/cnative/specs/resource.py, workloads/paas_wl/paas_wl/cnative/specs/v1alpha1/bk_app.py, workloads/paas_wl/paas_wl/cnative/specs/v1alpha1/domain_group_mapping.py
Fix unittests failing in Kubernete 1.18 by removing null fields in CRD when being applid to cluster.
=> Fix unittests failing in Kubernete 1.18

apiserver/paasng/paasng/engine/display_blocks.py, apiserver/paasng/paasng/engine/views.py, apiserver/paasng/paasng/platform/applications/models.py, apiserver/paasng/paasng/publish/entrance/domains.py, apiserver/paasng/paasng/publish/entrance/exposer.py, apiserver/paasng/paasng/publish/entrance/subpaths.py, apiserver/paasng/paasng/publish/entrance/views.py, apiserver/paasng/paasng/publish/market/utils.py, apiserver/paasng/tests/conftest.py, apiserver/paasng/tests/extensions/bk_plugins/test_models.py, apiserver/paasng/tests/publish/conftest.py, apiserver/paasng/tests/publish/entrance/test_domains.py, apiserver/paasng/tests/publish/entrance/test_exposer.py, apiserver/paasng/tests/publish/entrance/test_subpaths.py, apiserver/paasng/tests/publish/market/test_utils.py, apiserver/paasng/tests/publish/sync_market/conftest.py, apiserver/paasng/tests/publish/test_entrance.py, apiserver/paasng/tests/utils/helpers.py, workloads/paas_wl/paas_wl/cluster/models.py, workloads/paas_wl/paas_wl/networking/ingress/addrs.py, workloads/paas_wl/paas_wl/platform/system_api/views.py, workloads/paas_wl/tests/cluster/test_models.py, workloads/paas_wl/tests/networking/ingress/test_addrs.py
本次调整后，所有地址计算算法合并入 `SubDomainAllocator` / `SubPathAllocator` 类。其他需要获取访问地址的地方，主要分为两类：
- 获取可访问的真实地址：`get_addresses()` / `get_exposed_url()` / ...
- 获取不保证可访问的预分布地址：`get_preallocated_*()` / ...
- 调整 `exposer.py`，删除所有的 `*Provider` 类型，直接使用 workloads 服务返回的真实地址替代
- 将 `get_default_entrance(s?)` 重构为 `get_preallocated_*` 函数，复用 `*Allocator` 算法模块
- 删除之前为云原生应用编写专用过渡函数 `get_*_live`，与普通应用使用同一套函数
- 调整应用地址相关，直接使用 workloads 返回的真实地址
- 调整 `user_preferred_root_domain` 的生效逻辑，仅在已有地址中做筛选，不再“造”地址
- 使用 `get_exposed_url()` 等函数获取访问地址时，不再返回应用市场地址
- ~当 sub_path_domains 中存在 reserved 为 True 和 False 的域名时，新做法不保证一定优先拿 reserved 为 False 的条目~
=> Refactor "exposer" module, use live addresses instead of fixed URLs generated by *Provider

apiserver/paasng/paasng/engine/controller/client.py, apiserver/paasng/paasng/platform/applications/views.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/paasng/platform/modules/views.py, apiserver/paasng/tests/utils/mocks/engine.py, workloads/paas_wl/paas_wl/platform/applications/models_utils.py, workloads/paas_wl/paas_wl/platform/system_api/urls.py, workloads/paas_wl/paas_wl/platform/system_api/views.py, workloads/paas_wl/paas_wl/resources/actions/delete.py, workloads/paas_wl/tests/api/system_api/conftest.py, workloads/paas_wl/tests/conftest.py, workloads/paas_wl/tests/platform/applications/test_models_utils.py, workloads/paas_wl/tests/platform/applications/test_struct_models.py
- fix: module deletion protections not working at all.
- workloads: add `delete_module_related_res` API
- workloads: refactor test fixture
- apiserver: use updated API for deleting module in order to delete related custom domains
=> Fix module/app deletion, delete related custom domains and other resources

apiserver/paasng/paasng/tracing/instrumentor.py, workloads/paas_wl/paas_wl/tracing/instrumentor.py
request 触发异常时(例如访问超时), 这个回调的 response 就有可能是 None
---
不需要额外的日志, opentelemetry 会将异常重新抛出去, `requests` 库的使用方处理异常即可
=> bugfix: opentelemetry requests-tracing allow response to be optional

apiserver/paasng/paasng/engine/controller/client.py, apiserver/paasng/paasng/utils/basic.py, workloads/paas_wl/paas_wl/platform/external/client.py, workloads/paas_wl/paas_wl/utils/basic.py
Besides the changes made in current PR, gunicron with async worker is also required to support connection polling, ref: https://docs.gunicorn.org/en/stable/faq.html#why-is-there-no-http-keep-alive
=> Turn on connection polling when requesting "workloads" from "apiserver"(and vice versa)

workloads/paas_wl/paas_wl/release_controller/hooks/entities.py, workloads/paas_wl/paas_wl/resources/base/controllers.py, workloads/paas_wl/paas_wl/resources/base/exceptions.py, workloads/paas_wl/paas_wl/utils/kubestatus.py, workloads/paas_wl/tests/resources/actions/test_exec.py, workloads/paas_wl/tests/resources/base/test_client.py, workloads/paas_wl/tests/resources/base/test_controllers.py
只要主容器退出, 就认为 pre-release-hook 执行完毕
=> fix: 调整 pre-release-hook 探测执行结束的探针逻辑为判断主容器是否正常退出, 以兼容 sidecar 容器

webfe/package_vue/src/views/dev-center/migration/index.vue, workloads/paas_wl/paas_wl/settings/__init__.py, workloads/poetry.lock
原来的写法需要配置的环境变量是 ` PAAS_WL_CELERY_TASK_DEFAULT_QUEUE`, 现在修改成直接从环境变量读取。
=> fix: 修复 workloads 指定 celery 队列名称的方式与 apiserver 不一致的问题

apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/app_rule.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/metric_label.py, apiserver/paasng/tests/monitoring/test_metric_label.py
兼容部分k8s集群返回的minor version 带 + 号， 如14+
=> fix: some k8s cluster return minor version endswith +

operator/api/v1alpha2/bkapp_webhook.go, operator/api/v1alpha2/bkapp_webhook_test.go, operator/api/v1alpha2/constants.go, operator/api/v1alpha2/names.go, operator/api/v1alpha2/names_test.go, operator/pkg/controllers/resources/names/names_test.go
operator 通过区分 BkApp name， 以支持多模块的实现
- webhook 中新增 annotations 校验逻辑
=============
多模块的设计说明：
以 app code 为 test4cnative 为例，它有两个模块 default, backend.
test4cnative 会对应两个 BkApp 模型
- default 模块: BkApp name = test4cnative
- backend 模块: BkApp name = test4cnative-m-backend
test4cnative 一共有两个命名空间
- 测试环境：bkapp-test4cnative-stag
- 正式环境：bkapp-test4cnative-prod
=> feat: add validate annotations with BkApp name in webhook

apiserver/paasng/paasng/plat_admin/system/urls.py, apiserver/paasng/paasng/plat_admin/system/views.py, operator/pkg/controllers/reconcilers/addons.go, operator/pkg/controllers/reconcilers/addons_test.go, operator/pkg/platform/external/addons.go, operator/pkg/platform/external/addons_test.go
参考 `paasng.dev_resources.servicehub.views.ModuleServicesViewSet.retrieve_specs`的实现，将retrieve_specs添加到系统接口中
=> feat: add retrieve_specs api in SysAddonsAPIViewSet

apiserver/paasng/paasng/engine/deploy/bg_wait/wait_bkapp.py, apiserver/paasng/paasng/engine/views.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/rules_tpl/oom_killed.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/__init__.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/app_rule.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/constants.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/generator.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/handlers.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/manager.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/tasks.py, apiserver/paasng/paasng/monitoring/monitor/apps.py, apiserver/paasng/paasng/monitoring/monitor/models.py, apiserver/paasng/paasng/monitoring/monitor/urls.py, apiserver/paasng/paasng/monitoring/monitor/views.py, apiserver/paasng/tests/monitoring/alert_rules/conftest.py, apiserver/paasng/tests/monitoring/alert_rules/test_api.py, apiserver/paasng/tests/monitoring/alert_rules/test_manager.py
对接蓝鲸监控：统一普通应用与云原生应用
- 根据应用类型分别配置 app_scoped_alert_codes 和 module_scoped_alert_codes
- 注册 refresh_rules handler。 部署和下线时，能够刷新告警规则(celery task)
=> support monitor rules for cnative app

apiserver/paasng/paasng/accounts/permissions/application.py
- Add type guiding on application_perm_check function
- Support `Module` type, this fixes type errors when calling API such as `GET .../modules/<name>/` via browser, which renders a Web page.
=> Add type guiding on application_perm_check(support Module)

apiserver/paasng/paasng/plat_admin/system/serializers.py, apiserver/paasng/paasng/plat_admin/system/views.py, apiserver/paasng/tests/plat_admin/test_system.py
命名调整为 bcs_cluster_id，减少与 Cluster model uuid 的歧义
=> refactor: replace cluster_id to bcs_cluster_id in ClusterNamespaceSLZ

apiserver/paasng/tests/plat_admin/test_system.py
=> test: fix test_list_by_code when bcs_cluster_id is empty string

apiserver/paasng/paas_wl/cnative/specs/addons.py, apiserver/paasng/paas_wl/cnative/specs/entities.py, apiserver/paasng/tests/paas_wl/cnative/specs/test_addons.py
目前如果不往 spec 里写 addon 列表，会导致不注入增强服务的环境变量
=> bugfix: 实现将增强服务配置注入到 bkapp manifest 的逻辑

webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-hook.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/deploy-process.vue
=> fix: 创建应用->进程配置与钩子命令无需判断应用类型

apiserver/paasng/paasng/accessories/bkmonitorv3/backend/apigw.py, apiserver/paasng/paasng/accessories/bkmonitorv3/backend/esb.py, apiserver/paasng/paasng/accessories/bkmonitorv3/client.py, apiserver/paasng/paasng/engine/deploy/release/operator.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/client.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/ascode/notice_tpl/notice.yaml.j2, apiserver/paasng/paasng/monitoring/monitor/alert_rules/config/generator.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/handlers.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/manager.py, apiserver/paasng/paasng/monitoring/monitor/alert_rules/tasks.py, apiserver/paasng/paasng/monitoring/monitor/models.py, apiserver/paasng/paasng/monitoring/monitor/serializers.py, apiserver/paasng/paasng/monitoring/monitor/urls.py, apiserver/paasng/tests/monitoring/alert_rules/conftest.py, apiserver/paasng/tests/monitoring/alert_rules/test_api.py, apiserver/paasng/tests/monitoring/alert_rules/test_manager.py
对接蓝鲸监控命名空间：
- 将告警规则增量初始化到 SaaS 应用空间
- 使用监控网关的 as_code_import_config API 下发告警规则
- 将告警规则与告警通知组进行解耦，以支持应用成员变更时，通知组的人员变更
=> apply alert rules in an incremental update manner

apiserver/paasng/paasng/accessories/servicehub/views.py
`list_provisioned_rels = mixed_service_mgr.list_provisioned_rels(env.engine_app)`
https://github.com/TencentBlueKing/blueking-paas/blob/12198a6e315672f38f1485471df0afb5d058491a/apiserver/paasng/paasng/accessories/servicehub/views.py#L408
根本问题在于 service_instance_id 只会在两种情况下进行绑定：
1. build 阶段
2. service bind 阶段，且 plan.is_eager = True （暂时看到的 plan 实例都是 false）
因此这个 bug 会在两种情况下出现：
1. 创建应用后，应用未部署，开启增强服务。
2. 创建应用，应用部署以后，再开启增强服务。
总结：开启增强服务后，只要不执行部署，就会有这个bug
=> fix: 增强服务配置信息展示有误

apiserver/paasng/paas_wl/bk_app/cnative/specs/crd/bk_app.py, apiserver/paasng/paas_wl/bk_app/cnative/specs/procs/quota.py, apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/tests/paas_wl/bk_app/cnative/specs/test_models.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py
获取 BkApp yaml 的接口中，隐藏待废弃的 cpu/memory 等字段
=> refactor: hide deprecated cpu/memory/imagePullPolicy when get BkApp yaml

apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/engine/deploy/release/operator.py
修复因为重构 bkapp_model 导致丢失 image_pull_policy(advanced_options) 传入的问题
=> fix: missing image_pull_policy from advanced_options when refactor bkapp_model

apiserver/paasng/paas_wl/infras/resources/generation/version.py
- Fix: application using Mapper v1 unable to scale process because the deployment name is wrong
=> Fix: application using Mapper v1 unable to scale process because the deployment name is wrong

apiserver/paasng/paas_wl/bk_app/cnative/specs/constants.py, apiserver/paasng/paas_wl/bk_app/cnative/specs/procs/quota.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_env_overlays.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py, operator/api/v1alpha1/bkapp_conversion_test.go, operator/api/v1alpha2/bkapp_types.go, operator/api/v1alpha2/bkapp_webhook_test.go, operator/api/v1alpha2/constants.go, operator/pkg/config/config.go, operator/pkg/controllers/resources/deployment_test.go, operator/pkg/controllers/resources/env_overlay.go, operator/pkg/controllers/resources/env_overlay_test.go
配额调整
- 调大了默认 limits 4C/768Mi, 去掉了 2C 套餐
-  mem requests 规则按照 Limit的 1/2 和 1/4, 小于 2048Mi 的按照 1/4 算
=> refactor: increase the default memory limit and remove the 2C cpu plan

operator/controllers/bkapp_controller_test.go, operator/pkg/controllers/reconcilers/deploy_action.go, operator/pkg/controllers/reconcilers/deployments.go, operator/pkg/controllers/reconcilers/hooks.go
更新 AppProgressing 和 AppAvailable 的条件流转, 目的是和 Generation 保持版本一致
=> refactor: update condition AppProgressing & AppAvailable transition

apiserver/paasng/paasng/platform/applications/serializers/__init__.py, apiserver/paasng/paasng/platform/applications/serializers/cnative.py, apiserver/paasng/paasng/platform/applications/views.py, apiserver/paasng/paasng/platform/bkapp_model/importer/serializers.py, apiserver/paasng/paasng/platform/modules/entities.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/paasng/platform/modules/serializers.py, apiserver/paasng/paasng/platform/modules/views.py, apiserver/paasng/tests/api/test_applications.py, apiserver/paasng/tests/api/test_modules.py
云原生应用/模块的创建接口调整：
- 去除依赖 BkApp 模型(版本)的 manifest 参数，由 bkapp_spec 替换
=> refactor: use bkapp_spec instead of manifest in create cnative app api

apiserver/paasng/paas_wl/workloads/images/serializers.py, apiserver/paasng/paasng/platform/applications/serializers/cnative.py, apiserver/paasng/paasng/platform/modules/serializers.py, apiserver/paasng/paasng/platform/modules/views.py
=> refactor: do not validate image credential when creating a cloud-native module

operator/api/v1alpha2/constants.go, operator/go.mod, operator/go.sum, operator/pkg/controllers/reconcilers/deployments.go, operator/pkg/controllers/reconcilers/deployments_test.go, operator/pkg/controllers/reconcilers/utils_test.go, operator/pkg/controllers/resources/deployment.go, operator/pkg/controllers/resources/deployment_test.go, operator/pkg/controllers/svcdisc/configmap.go, operator/pkg/controllers/svcdisc/configmap_test.go
In current implemetation, if the operator change the logic related with constructing the deployment body of bkapp, such as modify the default resource requirements, it will make all deployments to start a rolling update because the spec has change.
This PR fix this by doing a semantic compare between the syned and input bkapp spec when reconciling.
=> Fix: avoid rolling out deployments of all bkapps when releasing new version of operator

apiserver/init.sh, builder-stack/README.md, builder-stack/cloudnative-buildpacks/builders/heroku-builder/builder.toml, builder-stack/cloudnative-buildpacks/buildpacks/bk-buildpack-go/shim/buildpack.toml, builder-stack/cloudnative-buildpacks/buildpacks/bk-buildpack-nodejs/shim/buildpack.toml, builder-stack/cloudnative-buildpacks/buildpacks/bk-buildpack-python/shim/buildpack.toml, builder-stack/cnb-builder-shim/cmd/build-init/main_test.go
外发的 init.sh 里已经写死过名称，云原生应用就往这名称靠吧。
=> minor: 统一 buildpack 名称; 增加初始化云原生 buildpack 的脚本

apiserver/paasng/paasng/accessories/log/client.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/definitions.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/log/__init__.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/log/client.py, apiserver/paasng/paasng/utils/es_log/misc.py
以前的写法是 bkbase 的接口返回格式。换对接的 API 时没改代码。
如何因为 bklog 未对外开放 esquery_mapping 接口，所以实现不了 ESClient 那种泛用性的实现，只能加个 `filterFields` 字段凑合用。
=> fix: 修复由于日志平台未开放 esquery_mapping 接口导致无法正常聚合字段的问题

apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/tests/api/test_applications.py
修复：初始化模块时，不应该设置 ModuleProcessSpec 的 image_credential_name
=> fix: incorrectly set image_credential_name in ModuleProcessSpec 

apiserver/paasng/paasng/plat_admin/admin_cli/mapper_version.py
- Fix: adm_stats/res_mapper_v1 unable to display envs that has an empty mapper version
=> Fix: adm_stats/res_mapper_v1 unable to display envs that has an empty mapper version

apiserver/paasng/support-files/apigw/resources.yaml
如果 apigw 以后不支持 get 请求里带上 body, 那这个接口标准运维用得上。
=> minor: 添加新网关接口 search_structured_log_with_post

webfe/package_vue/src/views/dev-center/app/engine/env-vars/index.vue
=> fix: 基础镜像的应用无法再保存“自定义运行时”，去除前端限制

apiserver/paasng/paasng/utils/validators.py, apiserver/paasng/tests/api/test_modules.py, apiserver/paasng/tests/paasng/platform/engine/utils/test_source.py
背景：目前如果进程名称有大写字母，构建后运行也会报错启动失败。
改动：将报错信息提早到准备阶段就触发。
=> minor: 进程名称显式限制不允许大写字母

builder-stack/heroku-buildpacks/bk-buildpack-python/hooks/setup-user-compile-hook
- Fix: pre/post-compile hooks using dash naming style fail to execute(python-buildpack)
=> Fix: pre/post-compile hooks using dash naming style fail to execute(python-buildpack)

webfe/package_vue/src/language/lang/en.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-module-list.vue
- Enhance: display a different label which include error detail when the first deployment failed
Screenshoot:
=> Enhance: display a different label which include error detail when the first deployment failed

operator/controllers/bkapp_controller.go, operator/pkg/controllers/predicates/hooks.go
解决由于 Pod 被 kubelet 更新 status 时也会触发调和循环的问题。
目前已知会错误触发调和循环的场景:
- pod 无法拉取镜像, kubelet 会不停更新 status (imagePullBackOff <-> ErrImagePull 来回切换)
- pod 重启, 不管什么原因，重启就会更新 status 的 restartCount (进程的 Pod 重启也会触发调和）
=> feature: 实现 HookFinishedPredicate 控制仅当 Hook 执行成功时触发调和循环

operator/controllers/bkapp_controller.go, operator/controllers/bkapp_controller_test.go, operator/controllers/domaingroupmapping_controller.go, operator/pkg/controllers/reconcilers/deploy_action.go, operator/pkg/controllers/resources/deployment.go, operator/pkg/controllers/resources/env_overlay.go, operator/pkg/controllers/resources/ingress_plugins.go
由于 DomainGroupMappingReconciler 和 BkAppReconciler 都需要更新 bkapp 的 status. 在一次部署过程会出现多次冲突。
这个 PR 将更新操作调整成 merge-patch+json. 尽可能减少冲突次数。
调整前会出现多次以下日志，调整后该日志消失:
```
Error updating status for processed item ...
Error updating status for processed item ...
Error updating status for processed item ...
```
这个改动可以导致报错次数变少
=> enhance: 使用 merge-patch 更新 status, 避免日志频繁报冲突

apiserver/paasng/paasng/accessories/smart_advisor/tagging.py, apiserver/paasng/tests/paasng/accessories/smart_advisor/test_tagging.py
- Fix: error tagging requirements when the file is using wrong encoding
This is a frequently captured error in sentry.
=> Fix: error tagging requirements when the file is using wrong encoding

apiserver/paasng/paasng/platform/applications/mixins.py
- Enhance: return 404 instead of server error when module not found
This is a frequently captured error in sentry.
=> Enhance: return 404 instead of server error when module not found

apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/bkapp_model/utils.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_utils.py
- 修复：BKPAAS_, 增强服务等环境变量被用户自定义变量覆盖的问题
=> fix: cnative app build-in env vars overridden by user-defined vas

apiserver/paasng/paas_wl/bk_app/deploy/actions/__init__.py, apiserver/paasng/paas_wl/bk_app/deploy/actions/deploy.py, apiserver/paasng/paas_wl/bk_app/deploy/app_res/client.py, apiserver/paasng/paas_wl/bk_app/deploy/app_res/controllers.py, apiserver/paasng/paas_wl/bk_app/deploy/app_res/utils.py, apiserver/paasng/paas_wl/bk_app/deploy/processes.py, apiserver/paasng/paas_wl/bk_app/processes/kres_entities.py, apiserver/paasng/paas_wl/bk_app/processes/kres_slzs.py, apiserver/paasng/paas_wl/core/resource.py, apiserver/paasng/paas_wl/infras/resources/base/kres.py, apiserver/paasng/paas_wl/infras/resources/generation/mapper.py, apiserver/paasng/paas_wl/infras/resources/generation/v1.py, apiserver/paasng/paas_wl/infras/resources/generation/v2.py, apiserver/paasng/paas_wl/infras/resources/generation/version.py, apiserver/paasng/paasng/plat_admin/admin_cli/deploy.py, apiserver/paasng/paasng/plat_admin/admin_cli/management/commands/adm_mapper_v1.py, apiserver/paasng/tests/paas_wl/bk_app/deploy/actions/test_deploy.py, apiserver/paasng/tests/paas_wl/bk_app/deploy/app_res/test_client.py, apiserver/paasng/tests/paas_wl/bk_app/deploy/app_res/test_controllers.py, apiserver/paasng/tests/paas_wl/bk_app/processes/test_controllers.py, apiserver/paasng/tests/paas_wl/bk_app/processes/test_managers.py, apiserver/paasng/tests/paas_wl/infras/cluster/test_utils.py, apiserver/paasng/tests/paas_wl/infras/resources/generation/test_generation.py
- Fix: Unable to delete obsolete process when deploying an archived application
- Refactor: Refactor the obsolete processes cleaner for better clarity
- Refactor: Simplify the generation module by deleting some unnecessary abstractions
- Refactor: Remove process-related operation from SchedulerClient
=> Fix: unable to delete process & Refactor ObsoleteProcessesCleaner & Generation module and etc

apiserver/paasng/paasng/platform/applications/serializers/app.py
- Add "type" field to the "/applications/lists/latest/" API so that the web frontend can know what type of navigation to use, this fixes a bug where hitting the "back" button on the cloud-native application page doesn't work as intended. @leafage-collb
=> enhance: add "type" field in latest operated applications API

builder-stack/heroku-buildpacks/bk-buildpack-go/hooks/post-compile, builder-stack/heroku-buildpacks/bk-buildpack-go/hooks/pre-compile, builder-stack/heroku-buildpacks/bk-buildpack-go/patchs/buildpack/bin/compile.patch
- refactor: 移除对 GOVERSION 探测的 patch(buildpack 本身已有相关逻辑)
- refactor: 移除意义不明的 patch 代码
- fix: go 语言的 buildpack 在构建后期会输出大量无法删除的权限错误
=> Fix buildpack go

apiserver/paasng/paasng/misc/feature_flags/constants.py, apiserver/paasng/paasng/settings/__init__.py, webfe/package_vue/index.html
绑定功能可使用源码应用已有的 API，并测试了镜像应用绑定源码后各项功能均正常。但该功能仅在特定版本启用，所以需要提供 FeatureFlag 给前端。
=> feat: 添加 FeatureFlag 用于前端控制镜像应用是否能绑定源码信息

apiserver/paasng/paas_wl/bk_app/processes/urls.py, apiserver/paasng/paas_wl/workloads/images/urls.py, apiserver/paasng/paas_wl/workloads/networking/egress/urls.py, apiserver/paasng/paas_wl/workloads/networking/entrance/urls.py, apiserver/paasng/paas_wl/workloads/networking/ingress/urls.py, apiserver/paasng/support-files/apigw/resources.yaml, apiserver/paasng/tests/paas_wl/api/test_image_credential.py
- Update APIs which starts with "/svc_workloads/" to remove the prefix
- The API "process.list" was excluded from this CL because it's still being used in the API Gateway. It will be removed after we modify the API Gateway resource.
=> Update APIs which starts with "/svc_workloads/" to remove the prefix

apiserver/paasng/paas_wl/apis/admin/urls.py, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/applications/detail/engine/custom_domain.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/applications/detail/engine/log_config.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/applications/detail/engine/processes.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/platformmgr/certs.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/platformmgr/cluster_components.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/platformmgr/clusters.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/platformmgr/operator.html, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/platformmgr/process_spec_plans.html
Some admin pages use fixed API paths instead of calling the `url` function. If the platform was deployed with a path prefix, these paths could be incorrect and cause the webpage to fail to load resources. This PR fixes this by using `{% url ... %}`.
=> Fix: some admin pages use the wrong API path if the platform is deployed with a path prefix other than "/"

apiserver/paasng/locale/en/LC_MESSAGES/django.po, apiserver/paasng/paasng/platform/bkapp_model/serializers.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/tests/api/test_network_config.py
- Disallow duplicate entries when upsert svc-disc config
- Changed the behavior of `SvcDiscEntryBkSaaSSLZ`: it sets `module_name` to None instead of `default', because `None` means that the **default module** is always used, while `default' refers to the module named "default" even if it is not the real "default" module.
- Change the permission level for APIs: DomainResolutionViewSet / SvcDiscConfigViewSet
- Some translation issues fixed
=> Enhance: disallow duplicate entries when upsert svc-disc config & other fixes

apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/declarative/deployment/controller.py, apiserver/paasng/paasng/platform/declarative/deployment/validations/v2.py, apiserver/paasng/paasng/platform/declarative/handlers.py
重构 `ProcessesManifestConstructor.get_command_and_args`,  以处理 #1141 带来的新模型影响
=> fix: generate incorrect command/args for smart app after introducing VER_3

operator/pkg/controllers/bkapp/deploy_action.go, operator/pkg/controllers/bkapp/hooks/hooks.go, operator/pkg/controllers/bkapp/hooks/resources/hooks.go, operator/pkg/controllers/bkapp/svcdisc/mutator.go, operator/pkg/controllers/bkapp/svcdisc/mutator_test.go
- Fix: the pre-release pod missing svc-disc env variables.
- Refactor: replace `BuildPreReleaseHook` call in deploy_action.go with `IsPreReleaseProgressing`
=> Fix: the pre-release pod missing svc-disc env variables

apiserver/paasng/paasng/celery.py
- Fix: ignore celery logging set up and use project logging settings instead
=> Fix: ignore celery logging set up and use project logging settings instead

webfe/package_vue/src/store/modules/log.js, webfe/package_vue/src/views/dev-center/app/engine/log/access-log.vue, webfe/package_vue/src/views/dev-center/app/engine/log/custom-log.vue
- 日志查询-结构化日志/访问日志访问记录表格时间和纪录时间制不一致
- 日志查询-标准化日志点击漏斗不能收回搜索框，参考访问日志漏斗
- 日志查询表格在数据量小于等于10条时，建议隐藏分页器
- 日志检索表格缺少计数统计，不符合设计规范
- 日志标题&字段设置吸顶
=> fix: 日志体验提单修复

webfe/package_vue/package.json, webfe/package_vue/src/App.vue, webfe/package_vue/static/login_success.html
=> refactor: 使用npm包统一登录弹窗方案

apiserver/paasng/paas_wl/bk_app/deploy/processes.py, apiserver/paasng/paasng/platform/engine/constants.py, apiserver/paasng/paasng/platform/engine/serializers.py, apiserver/paasng/paasng/platform/modules/constants.py, apiserver/paasng/paasng/platform/sourcectl/models.py, apiserver/paasng/tests/api/test_engine.py
改动点：
- 部署接口增加对 version_type 的选项校验，处理由于误传 image 类型，导致 Deployment.get_version_info 异常的问题
- 普通应用扩缩容同步修改 ModuleProcessSpec 副本数(主要解决旧镜像应用的问题)。
=> fix: scale not work when deploy again for old image app

webfe/package_vue/src/store/modules/module.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue
- 云原生仅镜像应用部署时，version_type 统一设置值为 tag
- 模块基本信息接口路补充
=> fix：云原生仅镜像应用部署时，version_type 统一设置值为 tag、模块基本信息接口路补充

webfe/package_vue/index.html, webfe/package_vue/src/components/paas-app-nav.vue, webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/components/usage-guide/index.vue, webfe/package_vue/src/store/modules/cloud-api.js, webfe/package_vue/src/views/dev-center/app/engine/cloud-deployment/index.vue, webfe/package_vue/src/views/dev-center/app/services/instance.vue, webfe/package_vue/src/views/dev-center/create-app/cloud.scss, webfe/package_vue/src/views/dev-center/create-app/cloud.vue, webfe/package_vue/src/views/dev-center/create-app/success-git.vue
- 出海版插件支持 go 语言
- 切换应用时，左侧菜单频繁折叠打开
- favicon应该和logo一致
- 增强服务实例详情：使用指南的宽度可以拖动
- 云原生仅镜像应用部署时，version_type 统一设置值为 tag
- 模块基本信息接口路补充
=> 出海版插件支持 go 语言、favicon应该和logo一致、其他体验问题修复

apiserver/paasng/paasng/platform/sourcectl/controllers/bare_git.py, apiserver/paasng/paasng/platform/sourcectl/git/client.py, apiserver/paasng/tests/paasng/platform/sourcectl/git/test_git_client.py
- Let touch() call list_remote_raw(), a new function that only run `ls-remote` and don't parse the output
- Update list_remote() so that it never failed on parsing
=> Fix: list_remote() failed to parse the result when warning message showed up

apiserver/paasng/paasng/bk_plugins/pluginscenter/sourcectl/tencent.py, apiserver/paasng/paasng/platform/engine/constants.py, apiserver/paasng/paasng/platform/engine/deploy/start.py, apiserver/paasng/paasng/platform/engine/management/commands/deploy_bkapp.py, apiserver/paasng/paasng/platform/engine/models/deployment.py, apiserver/paasng/paasng/platform/engine/views/deploy.py, apiserver/paasng/paasng/platform/sourcectl/controllers/docker.py, apiserver/paasng/paasng/platform/sourcectl/controllers/gitee.py, apiserver/paasng/paasng/platform/sourcectl/controllers/github.py, apiserver/paasng/paasng/platform/sourcectl/controllers/package.py, apiserver/paasng/paasng/platform/sourcectl/models.py, apiserver/paasng/tests/paasng/platform/engine/test_deployment.py
背景 pr #1281：
- 镜像模式的 smart 应用，其 `version_type`，由 image 调整为 tag
说明：根据现在  `Deployment.get_version_info` 的实现，`version_type` 值为 `image` 时 只用于云原生应用选择已构建的镜像部署时的场景
=> fix: smart image app use version_type=image when deploying

apiserver/paasng/paas_wl/bk_app/cnative/specs/crd/bk_app.py, apiserver/paasng/paasng/accessories/servicehub/sharing.py, apiserver/paasng/paasng/platform/bkapp_model/importer/addons.py, apiserver/paasng/paasng/platform/bkapp_model/importer/importer.py, apiserver/paasng/paasng/platform/bkapp_model/importer/serializers.py, apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/declarative/application/validations/v3.py, apiserver/paasng/tests/conftest.py, apiserver/paasng/tests/paasng/misc/monitoring/alert_rules/conftest.py, apiserver/paasng/tests/paasng/platform/bkapp_model/importer/test_importer.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_manifest.py, apiserver/paasng/tests/paasng/platform/declarative/application/v3/test_controller.py, apiserver/paasng/tests/paasng/platform/declarative/application/v3/test_validations.py, apiserver/paasng/tests/paasng/platform/declarative/test_slzs.py
- feat: add shared services support when generating manifest
- feat: bkapp model import support addons field(not implemented)
=> feat: add shared services support when generating manifest

apiserver/paasng/tests/paasng/platform/mgrlegacy/cnative/conftest.py
=> test: only create default cluster if not exist in _set_default_cluster

apiserver/paasng/paasng/accessories/servicehub/exceptions.py, apiserver/paasng/paasng/accessories/servicehub/local/manager.py, apiserver/paasng/paasng/accessories/servicehub/remote/manager.py, apiserver/paasng/paasng/accessories/servicehub/views.py, apiserver/paasng/tests/paasng/accessories/servicehub/remote/test_manager.py, apiserver/paasng/tests/paasng/accessories/servicehub/test_manager.py
- enhance: improve the error msg when no plans can be found binding service
Currently, users might see "增强服务绑定失败: can not bind a plan" error message when trying to bind a service using the wrong spec.
=> enhance: improve the error msg when no plans can be found binding service

webfe/package_vue/src/components/paas-header.vue, webfe/package_vue/src/components/paas-module-bar.vue, webfe/package_vue/src/main.js, webfe/package_vue/src/store/index.js, webfe/package_vue/src/views/dev-center/app/basic-config/info.vue, webfe/package_vue/src/views/dev-center/create-app/comps/top-bar.vue, webfe/package_vue/src/views/dev-center/create-app/success-git.scss, webfe/package_vue/src/views/dev-center/create-app/success-simple.vue, webfe/package_vue/src/views/dev-center/create-app/success-smart.vue, webfe/package_vue/src/views/plugin-center/create-plugin/success.vue
- 模块管理国际化补充
- 修改应用名称loading问题修复，以及本地更新
- 创建应用成功时，切换英文后，导航栏中英文切换按钮和退出登录按钮消失
- 创建应用成功页兼容通知中心
=> fix: 测试提单修复

webfe/package_vue/src/views/dev-center/app/engine/deployment/comps/deploy-action/index.vue
- 普通应用-部署分支为 image 时，部署弹框 imagePullPolicy 没有展示出来
=> fix：普通应用-部署分支为 image 时，部署弹框 imagePullPolicy 没有展示出来

webfe/package_vue/src/views/dev-center/app/market/visible-range.vue
=> update: 应用市场可见范围为空时应该提示默认全局可见

apiserver/paasng/paasng/platform/declarative/deployment/validations/v2.py, apiserver/paasng/paasng/platform/engine/deploy/building.py
If the developer defines a process with a name longer than the maximum allowed value, the deployment will fail. But the error message will be "cannot read procfile" instead of "process name is invalid". That's because the "handle-description" phase always failed silently for non-cnative apps, and the real cause was swallowed and another not-so-related exception was thrown instead, which generates a more vague error message.
This PR changes that behavior by always raising the validation error when handling the app description file.
=> fix: show the correct message when process name defined in app_desc.yaml is too long

apiserver/paasng/conf.yaml.tpl, apiserver/paasng/paas_wl/workloads/networking/ingress/managers/domain.py, apiserver/paasng/paas_wl/workloads/networking/ingress/managers/subpath.py, apiserver/paasng/paasng/platform/applications/views.py, apiserver/paasng/paasng/platform/engine/deploy/archive/operator.py, apiserver/paasng/paasng/settings/workloads.py, apiserver/paasng/tests/paas_wl/workloads/networking/ingress/managers/test_domain.py, apiserver/paasng/tests/paas_wl/workloads/networking/ingress/managers/test_subpath.py, operator/api/v1alpha1/projectconfig_types.go, operator/api/v1alpha1/projectconfig_types_test.go, operator/config/crd/bases/paas.bk.tencent.com_projectconfigs.yaml, operator/main.go, operator/pkg/config/config.go, operator/pkg/controllers/dgroupmapping/ingress/builder.go, operator/pkg/controllers/dgroupmapping/ingress/builder_test.go
- 新增：支持为独立域名 ingress 设置 kubernetes.io/ingress.class
- 修复：云原生独立域名配置  kubernetes.io/ingress.class 不生效的问题
=> feat: support set custom domain ingress class separately

apiserver/paasng/paasng/infras/accounts/permissions/application.py, apiserver/paasng/paasng/platform/environments/views.py
- fix: ModuleEnvRoleProtectionViewSet unable to do permission check
=> fix: ModuleEnvRoleProtectionViewSet unable to do permission check

apiserver/README.md
=> docs: update apiserver/README.md

webfe/package_vue/src/components/user/member-selector/member-selector.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-dialog.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-history.vue, webfe/package_vue/src/views/dev-center/app/engine/cloud-deploy-manage/comps/deploy-module-list.vue, webfe/package_vue/src/views/dev-center/app/engine/deployment/deploy-history.vue
- 普通应用当前应用不支持 list-watch 进程信息
- 仓库地址显示问题修复
- 部署历史查询操作优化
=> fix：体验提单修复

apiserver/paasng/paasng/infras/accounts/permissions/application.py, apiserver/paasng/paasng/settings/__init__.py
- fix: perm_insure checking missing late extend django apps
The project supports registering additional applications using the `settings.EXTRA_INSTALLED_APPS` configuration. These applications may extend the root URLs. Change the order of "perm_insure" to the last to make sure it can check all URLs.
=> fix: perm_insure checking missing late extend django apps

apiserver/paasng/paasng/plat_admin/admin42/serializers/templates.py, apiserver/paasng/paasng/plat_admin/admin42/templates/admin42/configuration/templates.html, apiserver/paasng/paasng/platform/templates/models.py
fix: 模板类型为插件的情况下，二进制包存储配置可为空
fix: 前端模板类型为插件时不显示
=> fix: fixed templates filling logic in admin42

apiserver/paasng/paasng/platform/sourcectl/views.py
- refactor: add missing error logs(view level) when getting repo failed
=> refactor: add missing error logs(view level) when getting repo failed

apiserver/Dockerfile, apiserver/dev_utils/unittest/Dockerfile.devops.unittest
fix: docker build fails because unexpected env var with empty value overrides the value in the settings file.
=> fix: docker build fails because unexpected env var with empty value overrides the settings

apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/env_vars.py, apiserver/paasng/paasng/platform/bkapp_model/serializers/serializers.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/paasng/platform/declarative/deployment/controller.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/tests/api/bkapp_model/test_bkapp_model.py, apiserver/paasng/tests/api/test_modules.py, apiserver/paasng/tests/paasng/platform/bkapp_model/entities_syncer/test_env_vars.py, apiserver/paasng/tests/paasng/platform/bkapp_model/entities_syncer/test_processes.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v3/test_probes.py
-  app_desc.yaml 未设置环境变量时，清空对应模块的 PresetEnvVariable
-  单独维护的 probes 只有普通应用解析时适用，云原生应用使用 ModuleProcessSpec 中的 probes
-  port 没有正确赋值给 target_port. 修复对应的单元测试
=> fix: delete PresetEnvVariable when not set

apiserver/paasng/paasng/misc/audit/service.py, apiserver/paasng/paasng/platform/bkapp_model/entities/__init__.py, apiserver/paasng/paasng/platform/bkapp_model/entities/proc_env_overlays.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/__init__.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/domain_resolution.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/env_vars.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/proc_env_overlays.py, apiserver/paasng/paasng/platform/bkapp_model/models.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/paasng/platform/declarative/deployment/controller.py, apiserver/paasng/paasng/platform/engine/configurations/preset_envvars.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/paasng/utils/structure.py, apiserver/paasng/tests/paasng/platform/bkapp_model/entities_syncer/test_env_vars.py, apiserver/paasng/tests/paasng/platform/bkapp_model/entities_syncer/test_proc_env_overlays.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_models.py, apiserver/paasng/tests/paasng/platform/engine/configurations/test_preset_envvars.py
- refactor: move functions out of sync_entities and add docs
- fix: sync_preset_env_vars won't remove existent data when only some env is given
=> refactor: move some functions out of sync_entities and add docs

operator/pkg/controllers/dgroupmapping/ingress/builder.go
修复：DomainGroupMapping 调和时，必须有 web 进程才能正确生成 ingress 的问题
=> fix: fail to generate ingresses(web process not found) in DomainGroupMapping

apiserver/paasng/paasng/accessories/log/client.py, apiserver/paasng/paasng/accessories/log/constants.py, apiserver/paasng/paasng/accessories/log/serializers.py, apiserver/paasng/paasng/accessories/log/views/logs.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/exceptions.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/log/__init__.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/log/client.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/log/exceptions.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/views.py
- 限制日志查询的最大窗口，避免查询 10,000 条以上的日志报错
- 修复插件查询日志时，未初始化配置导致异常问题
- 用户输入语法错误，API 返回错误码，记录错误日志即可，不抛 500 异常
- 日志平台 API 返回 result=false，记录错误日志，返回错误码，避免后续抛出 500 异常
- 修复插件查询日志时未指定主模块导致异常问题
以下是符合预期的异常，不用处理
- 查询标准输出日志时，scroll id 失效等导致 ES 查询异常
- 调用 bklog API 504 、连接超时等
=> fix: 修复日志相关 Sentry 异常

apiserver/paasng/paasng/settings/__init__.py
=> fix: 带端口的镜像地址解析问题 #1576

apiserver/paasng/paasng/platform/bkapp_model/entities/processes.py, apiserver/paasng/paasng/platform/declarative/deployment/controller.py, apiserver/paasng/paasng/platform/declarative/deployment/resources.py, apiserver/paasng/paasng/platform/declarative/entities.py, apiserver/paasng/paasng/platform/declarative/exceptions.py, apiserver/paasng/paasng/platform/declarative/handlers.py, apiserver/paasng/paasng/platform/declarative/serializers.py, apiserver/paasng/paasng/platform/engine/configurations/source_file.py, apiserver/paasng/paasng/platform/engine/deploy/building.py, apiserver/paasng/paasng/platform/engine/deploy/image_release.py, apiserver/paasng/paasng/platform/engine/exceptions.py, apiserver/paasng/paasng/platform/engine/models/deployment.py, apiserver/paasng/paasng/platform/engine/utils/patcher.py, apiserver/paasng/paasng/platform/engine/utils/source.py, apiserver/paasng/paasng/platform/smart_app/services/dispatch.py, apiserver/paasng/paasng/platform/smart_app/services/patcher.py, apiserver/paasng/paasng/platform/sourcectl/exceptions.py, apiserver/paasng/tests/paasng/platform/declarative/deployment/v2/test_controller.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/test_v1.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v2/test_deployment.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v2/test_probes.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v3/test_deployment.py, apiserver/paasng/tests/paasng/platform/declarative/handlers/v3/test_probes.py, apiserver/paasng/tests/paasng/platform/engine/configurations/test_config_var.py, apiserver/paasng/tests/paasng/platform/engine/deploy/test_building.py, apiserver/paasng/tests/paasng/platform/engine/utils/test_source.py, apiserver/paasng/tests/paasng/platform/smart_app/test_patcher.py
主要改动点：
- 优化部署流程与进程数据数据：将使用 declarative 解析“应用描述文件”变成必须步骤，同时把 Procfile 一并纳入解析流程中，以此简化当前部署流程中的多次“获取与对比”进程逻辑（`get_processes()`、对比与 sync 等），使进程数据在部署阶段一次性完成解析和数据持久化；
- 重构 declarative 模块：把 `handle_deployment()` 逻辑从现有 AppDescriptionHandler 中拆除，变为独立抽象；提升 `DeploymentDeclarativeController` 可读性并让它可以同时处理 procfile 数据；
已测试：
- 所有单测用例；
- 实际部署这些情况的应用：仅提供 app_desc、仅提供 procfile、二者都不提供、二者都提供并且进程数据冲突、app_desc 数据有误但 procfile 数据正常；
未测试存疑：
- ImageReleaseMgr 中的 S-Mart 应用分支逻辑
- 旧代码 `building.py` 中获取 desc_handler 后判断 `or not isinstance(handler, (AppDescriptionHandler, CNativeAppDescriptionHandler))`，用途存疑
- 相关代码：`"Currently only runtime configs such as environment variables declared in app_desc.yaml are applied."`
=> refactor: improve the process data sync logic & the declarative module

apiserver/paasng/paasng/accessories/cloudapi/constants.py, apiserver/paasng/paasng/accessories/cloudapi/serializers.py, apiserver/paasng/paasng/accessories/cloudapi/urls.py, apiserver/paasng/paasng/accessories/cloudapi/views.py, apiserver/paasng/tests/paasng/accessories/cloudapi/test_views.py
1. 续期使用原来的 API 和参数，API 网关侧支持已过期 API 直接续期（之前必须重新走申请逻辑）- 已验证
2. 新增批量 API 申请 API，可一次性申请多个网关下的多个 API（之前一次只能申请一个网关下的 API）- 已验证
3. 网关先发社区版最后再更新上云版本，先在社区版本验证了网关的功能
=> feat: 云 API 权限批量申请 API

webfe/package_vue/src/common/platform-config.js
- 全局配置：BK_SHARED_RES_URL 未设置时，不应该发起请求
=> fix: 全局配置：BK_SHARED_RES_URL 未设置时，不应该发起请求

webfe/package_vue/src/common/platform-config.js, webfe/package_vue/src/views/dev-center/index.vue
- 应用列表tooltips鼠标悬浮问题修复
- 全局配置：BK_SHARED_RES_URL 未设置时，不应该发起请求
=> fix：全局配置：BK_SHARED_RES_URL 未设置时，不应该发起请求 & 应用列表tooltips鼠标悬浮问题修复

apiserver/init.sh
- cnb 的 v1.0.1 镜像中， buildpack-go 已经到了 v191. 因此 init.sh 需要同步更新 buildpack-go 版本
=> chore: update buildpack-go(191) version in init.sh

apiserver/paasng/tests/paasng/platform/bkapp_model/test_manager.py
单测：测试 ModuleProcessSpecManager.sync_from_desc 方法中，同步副本数的逻辑
=> test: sync replicas in ModuleProcessSpecManager.sync_from_desc

apiserver/paasng/paasng/platform/bkapp_model/serializers/serializers.py
=> fix: do validate svc discovery redundantly

apiserver/paasng/paasng/settings/__init__.py
https://github.com/PyMySQL/PyMySQL/blob/a1ac8239c8bf79e7f1a17347b10d6e184221f9c1/pymysql/__init__.py#L57
pymysql 1.1.1+ 中已经内置兼容逻辑，无需再次 patch
=> fix: pymysql 1.1.1+ no longer need patch

apiserver/paasng/paas_wl/bk_app/processes/views.py, apiserver/paasng/paasng/platform/bkapp_model/entities/processes.py, apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/processes.py, apiserver/paasng/paasng/platform/bkapp_model/fieldmgr/__init__.py, apiserver/paasng/paasng/platform/bkapp_model/fieldmgr/fields.py, apiserver/paasng/paasng/platform/bkapp_model/fieldmgr/managers.py, apiserver/paasng/paasng/platform/bkapp_model/importer.py, apiserver/paasng/paasng/platform/bkapp_model/serializers/v1alpha2.py, apiserver/paasng/paasng/platform/bkapp_model/views.py, apiserver/paasng/paasng/platform/declarative/deployment/resources.py, apiserver/paasng/paasng/platform/declarative/deployment/validations/v2.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/tests/paasng/platform/bkapp_model/entities_syncer/test_processes.py, apiserver/paasng/tests/paasng/platform/bkapp_model/fieldmgr/test_managers.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_importer.py
- refactor: let sync_processes respect the management status of "replicas" and "autoscaling" fields
=> refactor: let sync_processes respect the management status of "replicas" and "autoscaling" fields

apiserver/paasng/paasng/platform/bkapp_model/entities_syncer/proc_env_overlays.py, apiserver/paasng/paasng/platform/bkapp_model/importer.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_importer.py
- fix: always reset overlay data when the base value was set on the process obj
=> fix: always reset overlay data when the base value was set on the process obj

apiserver/paasng/paasng/platform/bkapp_model/importer.py, apiserver/paasng/paasng/platform/declarative/deployment/validations/v2.py, apiserver/paasng/tests/paasng/platform/bkapp_model/test_importer.py
fix: handle None values in env_overlay fields to prevent unexpected behavior
=> fix: handle None values in env_overlay fields to prevent unexpected behavior

operator/config/default/manager_auth_proxy_patch.yaml, operator/go.mod
关联 Issue：https://github.com/TencentBlueKing/blueking-paas/issues/1768
注：Helm Charts 无需更新，因为脚本中有做替换：https://github.com/TencentBlueKing/blueking-paas/blob/777aa6c187a2c3515f117b74b0d3eb93742138ac/operator/scripts/update_helm_chart.py#L653
=> fix: replace kube-rbac-proxy image

apiserver/paasng/paas_wl/bk_app/cnative/specs/handlers.py, apiserver/paasng/paas_wl/workloads/networking/entrance/handlers.py, apiserver/paasng/tests/paasng/accessories/publish/entrance/test_triggers.py
=> fix: apply error ingress when cnative app switching default module

apiserver/paasng/paasng/accessories/paas_analysis/clients.py, apiserver/paasng/paasng/accessories/servicehub/remote/client.py, apiserver/paasng/paasng/infras/oauth2/api.py
- fix: improve JSON error handling in request wrappers
=> fix: improve JSON error handling in request wrappers

apiserver/paasng/paasng/platform/engine/utils/source.py, apiserver/paasng/paasng/platform/sourcectl/controllers/bare_git.py, apiserver/paasng/paasng/platform/sourcectl/controllers/bk_svn.py, apiserver/paasng/paasng/platform/sourcectl/controllers/gitee.py, apiserver/paasng/paasng/platform/sourcectl/controllers/github.py, apiserver/paasng/paasng/platform/sourcectl/controllers/gitlab.py, apiserver/paasng/paasng/platform/sourcectl/repo_controller.py
`try_to_preserve_meta_info` 是之前为在沙箱中保留 `.git` 而引入的
现在沙箱支持新的方式实现了代码提交，因此该参数不再需要保留，可以直接移除
=> fix: remove try_to_preserve_meta_info

apiserver/paasng/paasng/infras/accounts/constants.py
- 前端使用到了该配置项
- 用户在 admin42 中启用过会记录到数据库中，代码中删除后，API 中还是能查询到这个 featureflag ，故没有测试验证到
=> revert: ALLOW_PLUGIN_CENTER account featureflag

apiserver/paasng/paas_wl/bk_app/processes/processes.py, apiserver/paasng/paas_wl/infras/resources/base/bcs/__init__.py, apiserver/paasng/paas_wl/infras/resources/base/bcs/apigw.py, apiserver/paasng/paas_wl/infras/resources/base/bcs/client.py, apiserver/paasng/paasng/core/region/models.py, apiserver/paasng/paasng/core/region/states.py, apiserver/paasng/paasng/infras/accounts/serializers.py, apiserver/paasng/paasng/misc/plat_config/views.py, apiserver/paasng/paasng/platform/bk_lesscode/client.py, apiserver/paasng/paasng/settings/__init__.py, apiserver/paasng/tests/api/test_applications.py, apiserver/paasng/tests/api/test_modules.py, apiserver/paasng/tests/paasng/platform/test_lesscode.py, webfe/package_vue/src/views/dev-center/app/create-module/index.vue
1. 未启用 bcs 时，不调用 bcs API
2. 优化 bcs api 调用代码
2. 是否启用 lesscode 不再放到 region 配置中
3. 需要合入到 release-1.5 分支
4. helm chart 需要新增配置: ENABLE_BCS、ENABLE_BK_LESSCODE
=> feat: enable bcs and lesscode by settings config

apiserver/paasng/paas_wl/bk_app/cnative/specs/constants.py, apiserver/paasng/paasng/platform/bkapp_model/manifest.py, apiserver/paasng/paasng/platform/engine/deploy/bg_command/pre_release.py, apiserver/paasng/paasng/platform/engine/deploy/building.py, apiserver/paasng/paasng/platform/engine/deploy/image_release.py, apiserver/paasng/paasng/platform/engine/deploy/interruptions.py, apiserver/paasng/paasng/platform/engine/deploy/release/legacy.py, apiserver/paasng/paasng/platform/engine/deploy/release/operator.py, apiserver/paasng/paasng/platform/engine/models/deployment.py, apiserver/paasng/paasng/platform/engine/workflow/flow.py, apiserver/paasng/tests/api/core/tenant/test_tenant.py, apiserver/paasng/tests/paasng/platform/engine/deploy/test_pre_release.py, apiserver/paasng/tests/paasng/platform/engine/deploy/test_release.py, operator/api/v1alpha2/constants.go, operator/pkg/controllers/bkapp/deploy_action.go, operator/pkg/controllers/bkapp/deploy_action_test.go, operator/pkg/platform/deploy/deploy.go
- 移除 get_current_deployment 方法中释放部署锁的副作用。调整为中断部署时，释放部署锁
- 普通应用的 pre-release, app release, 云原生应用的 bkapp release，在它们的 start 入口增加中断逻辑，提升用户中断部署的有效性(还是看时机)
- 云原生增加 bkapp.paas.bk.tencent.com/last-deploy-status 注解，解决用户主动中断部署之后，再次部署应用时，由于 hook 仍处于progressing 直到现在的 15分钟设置，不能继续部署(调和)的问题
=> fix: user interrupt not work well sometimes

apiserver/paasng/paasng/core/region/models.py, apiserver/paasng/paasng/plat_admin/numbers/app.py, apiserver/paasng/paasng/platform/modules/serializers.py, apiserver/paasng/paasng/platform/sourcectl/connector.py, apiserver/paasng/paasng/platform/sourcectl/controllers/bk_svn.py, apiserver/paasng/paasng/platform/sourcectl/docker/models.py, apiserver/paasng/paasng/platform/sourcectl/models.py, apiserver/paasng/paasng/platform/sourcectl/repo_controller.py, apiserver/paasng/paasng/platform/sourcectl/serializers.py, apiserver/paasng/paasng/platform/sourcectl/signals.py, apiserver/paasng/paasng/platform/sourcectl/source_types.py, apiserver/paasng/paasng/platform/sourcectl/svn/admin.py, apiserver/paasng/paasng/platform/sourcectl/svn/server_config.py, apiserver/paasng/paasng/platform/sourcectl/type_specs.py, apiserver/paasng/paasng/platform/sourcectl/validators.py, apiserver/paasng/paasng/platform/sourcectl/views.py, apiserver/paasng/paasng/settings/__init__.py, apiserver/paasng/tests/api/test_sourcectl.py, apiserver/paasng/tests/paasng/platform/sourcectl/svn/test_server_config.py, apiserver/paasng/tests/paasng/platform/sourcectl/test_source_types.py, apiserver/paasng/tests/paasng/platform/sourcectl/test_validators.py
This PR removes the usage of the "region" property from the sourcectl application. Details:
- The bk_svn source control type no longer supports region-specific server configuration
- Remove "deploy_ver_for_update_svn_account" from settings/region_config
- Remove the create svn account API (no longer used)
**Further integrated tests on the bk_svn API are needed after merge.**
=> refactor: remove region parameter from various functions and models of sourcectl app

apiserver/paasng/paasng/core/tenant/user.py, apiserver/paasng/paasng/infras/accounts/models.py, apiserver/paasng/paasng/infras/accounts/views.py
- fix: remove unnecessary region parameter from Oauth2TokenHolder update
- docs: improve the docs of PrivateTokenHolder
=> fix: remove unnecessary region parameter from Oauth2TokenHolder update

apiserver/paasng/paasng/bk_plugins/pluginscenter/sys_apis/serializers.py, apiserver/paasng/tests/paasng/bk_plugins/pluginscenter/test_sys_apis.py
系统 API 的 serializers 继承的时候漏掉了 Meta 里面 插件 ID、名称 重复校验的 validators
=> fix: 迁移插件的 API 补充校验规则

apiserver/paasng/paasng/accessories/publish/entrance/serializers.py, apiserver/paasng/paasng/accessories/publish/entrance/views.py, apiserver/paasng/paasng/accessories/servicehub/views.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/iam_adaptor/policy/permissions.py, apiserver/paasng/paasng/bk_plugins/pluginscenter/views.py, apiserver/paasng/paasng/infras/accounts/permissions/application.py, apiserver/paasng/paasng/misc/monitoring/monitor/views.py, apiserver/paasng/paasng/platform/applications/views/application.py, apiserver/paasng/paasng/platform/applications/views/member.py, apiserver/paasng/paasng/platform/modules/views.py, apiserver/paasng/paasng/utils/views.py, apiserver/paasng/tests/paasng/test_utils/test_view.py
- refactor: remove action-perms decorator
reason:
```
WARNING/TODO: This decorator's functionality is flawed; it cannot replace the permission_classes
when the policy is set to "replace" because a permission check occurs before the handler function
is called. **STOP USING IT!** The existing code will be migrated.
```
=> refactor: remove action-perms decorator

apiserver/paasng/paas_wl/bk_app/processes/processes.py, apiserver/paasng/paas_wl/bk_app/processes/views.py, apiserver/paasng/tests/paas_wl/bk_app/processes/test_processes.py
- fix: server error when retrive a non-existing instance's "previous logs"
=> fix: server error when retrive a non-existing instance's "previous logs"

apiserver/paasng/paasng/accessories/services/providers/base.py, apiserver/paasng/tests/paasng/accessories/services/test_provider.py
config 里面的 kv 应该都是 str
uuid 类型会导致审计操作失败
=> fix: 修复资源池将 uuid 类型放入 config 导致的审计失败

apiserver/paasng/paas_wl/apis/admin/views/processes.py
environment 字段很早就从 ProcessSpecPlan 表中删除了
=> fix: 修复查询方案配置传入 search_term 参数后报错问题

apiserver/paasng/paasng/infras/accounts/entities.py, apiserver/paasng/paasng/infras/accounts/models.py, apiserver/paasng/paasng/infras/accounts/utils.py, apiserver/paasng/paasng/platform/applications/views/creation.py, apiserver/paasng/paasng/platform/modules/manager.py, apiserver/paasng/paasng/platform/modules/views.py, apiserver/paasng/paasng/platform/sourcectl/repo_controller.py, apiserver/paasng/paasng/platform/sourcectl/repo_provisioner.py, apiserver/paasng/paasng/utils/error_codes.py
1. 授权 token 的 scope 为：group:test1,  user:user
- 创建 groups/test2 项目组下的代码仓库成功
2. 授权 token 的 scope 为：group:test1
- 创建 group:test2 项目组下代码仓库失败，并报错
```
{
"code": "REPO_ACCESS_TOKEN_ERROR",
"detail": "您没有权限操作该代码仓库，请在“代码库管理”页面确认您的授权信息"
}
```
3. 授权 token 的 scope 为：group:test1
- 创建用户默认命名空间下创建仓库失败，并报错：
```
{
"code": "REPO_DEFAULT_SCOPE_PERMISSION_ERROR",
"detail": "必须使用“当前账号”授权才能在用户命名空间下创建仓库"
}
```
=> feat: 优化创建代码仓库时获取 oauth 凭证逻辑

cnb-builder-shim/rootfs/devsandbox/etc/s6-overlay/s6-rc.d/init-config/type, cnb-builder-shim/rootfs/devsandbox/etc/s6-overlay/s6-rc.d/init-config/up, cnb-builder-shim/rootfs/devsandbox/usr/bin/init-code-server-config
容器初始化时将 configmap 挂载进来的 settings.json 复制到另一目录以便编辑
**重要：该 PR 需要 cherry-pick 到 builder-stack-1.x**
=> feat: add s6 service init-config

apiserver/paasng/Makefile, apiserver/paasng/tests/api/accessories/proc_components/test_proc_components.py, apiserver/paasng/tests/paas_wl/bk_app/cnative/specs/test_resource.py, apiserver/paasng/tests/paasng/platform/sourcectl/test_source_types.py
- `Test__list_mres_by_env.test_list`, 添加 `spec.configuraiton` 字段
- 消除数据顺序对 assert 的影响
- 修改 `DJANGO_SETTINGS_MODULE` 路径
- 去除 pytest 的 `-s` 选项: 默认的日志级别为 INFO , 开启 `-s` 会输出大量低级别日志干扰
- 添加 `-l` 选项, 在出错时打印出调用栈, 方便排查问题
=> test: stabilize unittests by fixing order dependency and configuration
